puppetlabs/puppetlabs-packer

manifests/modules/packer/manifests/vmtools/params.pp
scripts/install-puppet-enterprise.sh
templates/debian-7.6/CHANGELOG
templates/debian-7.8/CHANGELOG
templates/debian-7.8/files/preseed.cfg
templates/debian-7.8/i386.virtualbox.base.json
templates/debian-7.8/i386.virtualbox.vagrant.nocm.json
templates/debian-7.8/i386.virtualbox.vagrant.pe.json
templates/debian-7.8/i386.virtualbox.vagrant.puppet.json
templates/debian-7.8/i386.vmware.base.json
templates/debian-7.8/i386.vmware.vagrant.nocm.json
templates/debian-7.8/i386.vmware.vagrant.pe.json
templates/debian-7.8/i386.vmware.vagrant.puppet.json
templates/debian-7.8/vagrantcloud.yaml
templates/debian-7.8/x86_64.ec2.nocm.json
templates/debian-7.8/x86_64.virtualbox.base.json
templates/debian-7.8/x86_64.virtualbox.vagrant.nocm.json
templates/debian-7.8/x86_64.virtualbox.vagrant.pe.json
templates/debian-7.8/x86_64.virtualbox.vagrant.puppet.json
templates/debian-7.8/x86_64.vmware.base.json
templates/debian-7.8/x86_64.vmware.vagrant.nocm.json
templates/debian-7.8/x86_64.vmware.vagrant.pe.json
templates/debian-7.8/x86_64.vmware.vagrant.puppet.json

This PR refreshes the vagrant boxes for Debian Wheezy.  The OS is bumped from 7.6 to 7.8, both Puppet and PE get version bumps, and a couple issues are addressed with the Virtualbox Guest Additions.

Refresh Debian Wheezy

---

templates/debian-7.8/files/inode.c.patch
templates/debian-7.8/i386.vmware.base.json
templates/debian-7.8/scripts/patch-tools.sh
templates/debian-7.8/x86_64.vmware.base.json

inode.c d_alias patch required to successfully compile the vmhgfs module
on Debian Wheezy

(maint) vmware tools vmhgfs patch for Wheezy

---

templates/debian-7.8/CHANGELOG
templates/debian-7.8/vagrantcloud.yaml

successful build of the vmhgfs module using the inode.c d_alias patch.
This commit will bump the box version of Wheezy that we ship to
vagrantcloud.

(maint) bump box version for Wheezy

---

manifests/modules/packer/manifests/networking/params.pp
manifests/modules/packer/manifests/puppet.pp
scripts/bootstrap-puppet.sh
templates/fedora-21/CHANGELOG
templates/fedora-21/files/ks.cfg
templates/fedora-21/i386.virtualbox.base.json
templates/fedora-21/i386.virtualbox.vagrant.nocm.json
templates/fedora-21/i386.virtualbox.vagrant.puppet.json
templates/fedora-21/i386.vmware.base.json
templates/fedora-21/i386.vmware.vagrant.nocm.json
templates/fedora-21/i386.vmware.vagrant.puppet.json
templates/fedora-21/vagrantcloud.yaml
templates/fedora-21/x86_64.virtualbox.base.json
templates/fedora-21/x86_64.virtualbox.vagrant.nocm.json
templates/fedora-21/x86_64.virtualbox.vagrant.puppet.json
templates/fedora-21/x86_64.vmware.base.json
templates/fedora-21/x86_64.vmware.vagrant.nocm.json
templates/fedora-21/x86_64.vmware.vagrant.puppet.json
templates/fedora-22/CHANGELOG
templates/fedora-22/files/ks.cfg
templates/fedora-22/i386.virtualbox.base.json
templates/fedora-22/i386.virtualbox.vagrant.nocm.json
templates/fedora-22/i386.vmware.base.json
templates/fedora-22/i386.vmware.vagrant.nocm.json
templates/fedora-22/vagrantcloud.yaml
templates/fedora-22/x86_64.virtualbox.base.json
templates/fedora-22/x86_64.virtualbox.vagrant.nocm.json
templates/fedora-22/x86_64.vmware.base.json
templates/fedora-22/x86_64.vmware.vagrant.nocm.json

This PR adds templates Fedora 21,22 Vagrant boxes.  21 contains nocm and puppet configurations.  22 currently only contains a nocm configuration.

(RE-4282,4464) Add Fedora Vagrant boxes

---

manifests/modules/packer/manifests/puppet.pp
manifests/modules/packer/manifests/vagrant.pp
templates/centos-5.11/vagrantcloud.yaml
templates/centos-6.6/vagrantcloud.yaml
templates/centos-7.0/vagrantcloud.yaml
templates/debian-6.0.10/vagrantcloud.yaml
templates/debian-7.8/vagrantcloud.yaml
templates/fedora-21/vagrantcloud.yaml
templates/fedora-22/vagrantcloud.yaml
templates/ubuntu-12.04/vagrantcloud.yaml
templates/ubuntu-14.04/vagrantcloud.yaml

This commit utilizes the profile.d directory to append the path to the
puppet-agent binaries to the user environment.
(maint) fix regression in determining repo type
A module was removed that provided a custom fact regarding yum repo type.
This commit removes the usage of that fact and relies on osfamily
instead.
(maint) bump puppet-agent
puppet-agent 1.2.2 is now available in the public repos.  This commit updates the 
vagrantcloud.yaml to reflect the updated version of puppet.

(RE-5101) add path for puppet-agent binaries

---

manifests/modules/packer/manifests/vsphere/params.pp
manifests/modules/packer/manifests/vsphere/repos.pp
manifests/modules/packer/templates/vsphere/redhat.rb.erb
templates/centos-5.11/i386.vsphere.nocm.json
templates/centos-5.11/x86_64.vsphere.nocm.json
templates/centos-6.6/i386.vsphere.nocm.json
templates/centos-6.6/x86_64.vsphere.nocm.json
templates/centos-7.0/x86_64.vsphere.nocm.json
templates/fedora-21/i386.vsphere.nocm.json
templates/fedora-21/x86_64.vsphere.nocm.json
templates/fedora-22/i386.vsphere.nocm.json
templates/fedora-22/x86_64.vsphere.nocm.json

This PR adds initial support for shipping CentOS and Fedora artifacts using the vSphere post-processor.  It's primarily intended to be used with the [vmpooler](https://github.com/puppetlabs/vmpooler).

(RE-6104) packer::vsphere support for CentOS and Fedora

---

templates/solaris-10u11/scripts/base.sh

This patch adds CSWcurl to the base build for Solaris 10. Having `curl` present
allows PE frictionless agent install to be used.

Solaris 10: Add curl to the base build

---

templates/solaris-11.2/files/ai.xml

Solaris now requires a "licence" package to be installed as a dependency of
many base packages; such as the GCC runtime libraries. Installation of this
package requires an `--accept` flag to be passed to PKG, which breaks
automated builds and installations which aren't expecting a licence check.
This patch adds the `release/evaluation` package to the automated install
manifest for Solaris 11.2.

Solaris 11.2: Add release/evaluation package

---

manifests/modules/packer/manifests/networking/params.pp
scripts/bootstrap-puppet.sh
templates/fedora-23/files/ks.cfg
templates/fedora-23/i386.vmware.base.json
templates/fedora-23/i386.vsphere.nocm.json
templates/fedora-23/x86_64.vmware.base.json
templates/fedora-23/x86_64.vsphere.nocm.json

This PR adds base and vsphere-nocm packer templates. The vSphere artifact is meant to be used with the vmpooler.

(RE-5464) Add Fedora 23 packer configs

---

templates/ubuntu-14.04/files/preseed.cfg
templates/ubuntu-14.04/i386.virtualbox.base.json
templates/ubuntu-14.04/i386.vmware.base.json
templates/ubuntu-14.04/x86_64.virtualbox.base.json
templates/ubuntu-14.04/x86_64.vmware.base.json

trusty was unintentionally bumped a point release during the previous
box update commits.  this reverts back to the original point release
and updates the preseed to prevent it being upgraded to the latest point.

(maint) trusty fixups

---

manifests/modules/packer/manifests/vsphere/networking.pp
templates/debian-6.0.10/i386.vsphere.nocm.json
templates/debian-6.0.10/x86_64.vsphere.nocm.json
templates/debian-7.8/i386.vsphere.nocm.json
templates/debian-7.8/x86_64.vsphere.nocm.json
templates/debian-8.0/i386.vsphere.nocm.json
templates/debian-8.0/x86_64.vsphere.nocm.json
templates/debian-8.2/i386.vsphere.nocm.json
templates/debian-8.2/x86_64.vsphere.nocm.json
templates/ubuntu-12.04/i386.vsphere.nocm.json
templates/ubuntu-12.04/x86_64.vsphere.nocm.json
templates/ubuntu-14.04/i386.vsphere.nocm.json
templates/ubuntu-14.04/x86_64.vsphere.nocm.json
templates/ubuntu-15.10/i386.vsphere.nocm.json
templates/ubuntu-15.10/x86_64.vsphere.nocm.json
templates/ubuntu-16.04/i386.vmware.base.json
templates/ubuntu-16.04/i386.vsphere.nocm.json
templates/ubuntu-16.04/x86_64.vmware.base.json
templates/ubuntu-16.04/x86_64.vsphere.nocm.json

This should address some issues were seeing with dhcpc on xenial.  Also update the module we're using for vsphere networking fixups ( so it's consistent on both debian and redhat based operating systems ).

(maint) bump the xenial daily build sha

---

manifests/modules/packer/manifests/vsphere.pp
manifests/modules/packer/manifests/vsphere/fw.pp
manifests/modules/packer/manifests/vsphere/networking.pp
templates/centos-7.2/x86_64.vsphere.nocm.json
templates/scientific-7.2/x86_64.vsphere.nocm.json

This commit disables the firewall for vsphere/vmpooler el7 artifacts and
extends the networking fixups to all of el7.

(maint) vsphere el7 fixups

---

templates/ubuntu-16.04/files/preseed.cfg
templates/ubuntu-16.04/i386.vmware.base.json
templates/ubuntu-16.04/i386.vsphere.nocm.json
templates/ubuntu-16.04/x86_64.vmware.base.json
templates/ubuntu-16.04/x86_64.vsphere.nocm.json

Prior images were based on nightly builds.  This is now the official release version. \o/
Also there was an issue with GRUB_CMDLINE_LINUX_DEFAULT="quiet" preventing tty1 coming up on boot - fixed that per: https://bugs.launchpad.net/ubuntu/+source/grub-installer/+bug/581796
Lastly set templates to headless.  The builders are choking on gui and the ability to just monitor over VNC is way better.

(RE-6581) Update Ubuntu 16.04 to Release

---

templates/ubuntu-16.04/CHANGELOG
templates/ubuntu-16.04/i386.virtualbox.base.json
templates/ubuntu-16.04/i386.virtualbox.vagrant.nocm.json
templates/ubuntu-16.04/i386.virtualbox.vagrant.puppet.json
templates/ubuntu-16.04/i386.vmware.base.json
templates/ubuntu-16.04/i386.vmware.vagrant.nocm.json
templates/ubuntu-16.04/i386.vmware.vagrant.puppet.json
templates/ubuntu-16.04/i386.vsphere.nocm.json
templates/ubuntu-16.04/vagrantcloud.yaml
templates/ubuntu-16.04/x86_64.virtualbox.base.json
templates/ubuntu-16.04/x86_64.virtualbox.vagrant.nocm.json
templates/ubuntu-16.04/x86_64.virtualbox.vagrant.puppet.json
templates/ubuntu-16.04/x86_64.vmware.vagrant.nocm.json
templates/ubuntu-16.04/x86_64.vmware.vagrant.puppet.json
templates/ubuntu-16.04/x86_64.vsphere.nocm.json

Add nocm and puppet configurations for Ubuntu 16.04 ( xenial ).  Shared folders for VMware artifacts are currently broken due to mitchellh/vagrant#6775.

(RE-7310) nocm and puppet Vagrant boxes for Xenial

---

.gitignore

This directory will go away shortly, but ignore to avoid clutter or
dodgy checkins.

(MAINT) Ignore drivers directory

---

manifests/modules/packer/files/vsphere/dhclient.conf
manifests/modules/packer/manifests/networking/params.pp
manifests/modules/packer/manifests/vsphere.pp
manifests/modules/packer/manifests/vsphere/networking.pp
manifests/modules/packer/manifests/vsphere/params.pp
manifests/modules/packer/templates/vsphere/redhat.rb.erb
scripts/bootstrap-aio.sh
scripts/bootstrap-puppet.sh
scripts/cleanup-aio.sh
templates/fedora-24/files/ks.cfg
templates/fedora-24/i386.vmware.base.json
templates/fedora-24/i386.vsphere.nocm.json
templates/fedora-24/x86_64.vmware.base.json
templates/fedora-24/x86_64.vsphere.nocm.json

The time has come to use the AIO vs older 3.8 binary.  This is necessary as default providers and library support has changed in modern operating systems, such as DNF and Python3
(Note we'll update this soonish to remove NFS all together and just do the fun stuff locally - better for the community and our sanity).
Added headless as monitoring the build over VNC is great for troubleshooting.
Set target vsphere NIC to vmxnet3 and removed dependency on specifying interface in bootstrap

(RE-7330) Update Fedora 24 Gold RC + Use AIO to provision

---

manifests/modules/packer/manifests/vsphere/params.pp
templates/ubuntu-12.04/i386.vmware.base.json
templates/ubuntu-12.04/i386.vsphere.nocm.json
templates/ubuntu-12.04/x86_64.vmware.base.json
templates/ubuntu-12.04/x86_64.vsphere.nocm.json
templates/ubuntu-14.04/i386.vmware.base.json
templates/ubuntu-14.04/i386.vsphere.nocm.json
templates/ubuntu-14.04/x86_64.vmware.base.json
templates/ubuntu-14.04/x86_64.vsphere.nocm.json

Newer Ubuntu images include rubygems package with ruby.  Older platforms require that for some legacy pipelines. Rebuilt imagines using AIO.

(SERVER-1409) Update Ubuntu 12.04/14.04 and include rubygems

---

manifests/windows/windows_template/manifests/local_group_policies.pp

Set of fixes to original puppet code by Glenn for miscellaneous registry
and other configuration settings to match WIndows Template
Configuration.
The fixes are:
1. Typo in Windows Error Reporting
2. Add Power/Hibernation configuration settings
3. Created C:\Crash_Dump directory
Have also addressed Administrator Autologin (RE-7512)

(RE-7460) Puppet cfg fixes for misc configuration

---

scripts/windows/generalize-packer.autounattend.xml
scripts/windows/start-boxstarter.ps1
templates/windows-2012r2/files/autounattend.xml
templates/windows-2012r2/files/windows-2012r2-x86_64-vmware-vsphere-cygwin.package.ps1
templates/windows-2012r2/files/windows-2012r2-x86_64-vmware.package.ps1
templates/windows-2012r2/x86_64.vmware.base.json
templates/windows-2012r2/x86_64.vmware.vsphere.cygwin.json

Setting the Autologon for the Administrator using a combination of Unattended installation with some additional registry settings in the box starter script.
This avoids having the show the Admin password in plain-text in the puppet code as originally attempted.
Have also Enabled Remote Desktop and Disabled UAC settings using box starter functions (RE-7513/RE-7383)

(RE-7152) Set the Administrator AutoLogon

---

scripts/windows/cleanup-host.ps1
scripts/windows/generalize-packer.autounattend.xml
scripts/windows/install-win-packages.ps1
scripts/windows/shutdown-packer.bat
scripts/windows/start-boxstarter.ps1
scripts/windows/windows-env.ps1
templates/windows-2012r2/files/autounattend.xml
templates/windows-2012r2/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2012r2/files/windows-2012r2-x86_64-vmware-vsphere-cygwin.package.ps1
templates/windows-2012r2/files/windows-2012r2-x86_64-vmware.package.ps1
templates/windows-2012r2/x86_64.vmware.base.json
templates/windows-2012r2/x86_64.vmware.vsphere.cygwin.json

Boxstarter (Restart) does not play well with packer once winrm is
enabled, so change the second phase configuration to work without
boxstarter.
This means adding some additional restarts into the packer provisioning
sequence.
This also incorporates #88 which will be closed.
Tickets addressed:
1. [RE-7663](https://tickets.puppetlabs.com/browse/RE-7663) - Fix Boxstarter restart issue
2. [RE-7458](https://tickets.puppetlabs.com/browse/RE-7458) - Install Chrome, Notepad and other utils
3. [RE-7457](https://tickets.puppetlabs.com/browse/RE-7457) - Install and license Sysinternals.

(RE-7663) Don't use boxstarter for later packer configuration

---

templates/windows-2016tp5/files/win-2016tp5-x86_64-std.pp
templates/windows-2016tp5/x86_64.vmware.vsphere.cygwin.json

This adds work to create the vsphere/cygwin packer image build scripts for
windows 2016 t.p. 5. This is a carbon copy of the 2012 work with some names changed.

(RE-7831) Add windows 2016 t.p. 5 vshpere/cygwin image

---

scripts/windows/install-cygwin.ps1

This is address a beaker permissions issue.
Need to copy the Cygwin_setup across to C:\Windows\system32 to overcome
an issue with the curl command in beaker testing. The beaker tests do
need fixing, but this is an interim workaround to prevent pipeline
breakages.
NB - this replaces #104 which was titled incorrectly.

(RE-7855) Copy Cygwin setup to system32 directory

---

manifests/windows/windows_template/files/master_preferences
manifests/windows/windows_template/manifests/chrome.pp
scripts/windows/puppet-configure.ps1
templates/windows-2012r2/files/win-2012r2-x86_64-std.pp

This allows the blank page (and other Chrome default settings) to be
defined. Also prevent the Chrome First Run dialogues.
Note - there is a bug in Chrome which causes the Chrome first run prompt
to run unless you use special incantations in the master_preferences
file. This edition of the file *seems* to work.
Note also the extra FACTER_xxx facts that need to be added. There may
still be a localisation issue lurking in this w.r.t. Program Files.
O btw - Google installs the 64 bit version into (x86)

(RE-7682) Add Chrome Default User Preferences

---

templates/windows-2012r2/x86_64.vmware.base.json
templates/windows-2012r2/x86_64.vmware.vsphere.cygwin.json

This pushes the built image up to the vmpooler vSphere Cluster.
Some MAINT modifications were also needed to the base image to allow it to run successfully on nelson/rodgers.

(RE-7618) Add vSphere Provisioner

---

templates/windows-2016tp5/files/windows-2016tp5-x86_64-vmware.package.ps1
templates/windows-2016tp5/x86_64.vmware.base.json

These commits will clean out files leftover from windows updates, and update the build scripts to only create one virtual disk file.

Clean windows update leftovers / only use one virtual disk file

---

templates/windows-2012r2/x86_64.vmware.base.json
templates/windows-2012r2/x86_64.vmware.vsphere.cygwin.json

This is required to build under packer on the Mac OS build machines.

(MAINT) Set headless operation

---

scripts/windows/clean-disk-dism.ps1
scripts/windows/cleanup-host.ps1
templates/windows-2012r2/files/autounattend.xml
templates/windows-2012r2/files/windows-2012r2-x86_64-vmware.package.ps1
templates/windows-2012r2/x86_64.vmware.base.json

A series of changes to the disk handling - the main one is to reduce the amount of disc traversed by ```sdelete``` to reduce the overall build time. 
(RE-7993) Change Disk Handling
1. Change disk type to Sparse Monolothic (Type 0), https://www.vmware.com/pdf/VirtualDiskManager.pdf
2. Move DISM cleanup to winrm section.
3. Limit initial disk size to 20G (to limit sdelete)
4. Extend partition to full size at final system preparation.

(RE-7993) Change Disk Handling

---

templates/windows-2016tp5/files/autounattend.xml
templates/windows-2016tp5/files/windows-2016tp5-x86_64-vmware.package.ps1
templates/windows-2016tp5/x86_64.vmware.base.json
templates/windows-2016tp5/x86_64.vmware.vsphere.cygwin.json

We recently changed the way windows 2012 builds work to reduce the image size
dramatically. This PR pulls 2016 in line with that as well as adds the post
processor to push up to vsphere

(maint) Update 2016 templates to include latest windows work

---

templates/windows-2016rtm/files/autounattend.xml
templates/windows-2016rtm/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2016rtm/files/generalize-packer.autounattend.xml
templates/windows-2016rtm/files/win-2016tp5-x86_64-std.pp
templates/windows-2016rtm/files/windows-2016rtm-x86_64-vmware.package.ps1
templates/windows-2016rtm/x86_64.vmware.base.json
templates/windows-2016rtm/x86_64.vmware.vsphere.cygwin.json

This is a copy of the TP5 build pointing to the latest RTM image.
The only major change was to make sure the KMS keys were specified
correctly as available in:
https://technet.microsoft.com/en-us/library/jj612867.aspx

(RE-7926) Add Windows 2016 RTM Build

---

templates/windows-2016rtm/files/autounattend.xml
templates/windows-2016rtm/x86_64.vmware.base.json
templates/windows-2016rtm/x86_64.vmware.vsphere.cygwin.json

Set the Windows Server Edition in the Unattend.xml so that we don't have
to use buggy boot-prompts.
This is an amendment to #115

(RE-7926) Set Install Image correctly

---

manifests/windows/windows_group_policy/manifests/local/machine_client_side_extensions.pp
manifests/windows/windows_group_policy/templates/gp_extensions.ps1
manifests/windows/windows_group_policy/templates/local_gpo.ps1
manifests/windows/windows_group_policy/templates/script_header.ps1

(maint) Update Windows Group Policy module for Powershell 5.1.14393  …
A bug has been identified on Powershell 5.1.14393 which has changed the way
STDIN is parsed (PowerShell/PowerShell#2068).
-  Trailing `{` is ignored on the next line.
Additional errors were found where:
- Would not parse a pipe over a new line e.g. this would not work
```
$newGPTContent = (Get-GPTIniContents |
ForEach-Object {
```
Must use instead
```
$newGPTContent = (Get-GPTIniContents | ForEach-Object {
```
- Would not parse an expression over a new line e.g. this would not work
```
$settingString = '[' + (
($guidList.GetEnumerator() | ForEach-Object -Process ....
) + ']'
```
Must use instead
```
$settingString = '[' + ( ($guidList.GetEnumerator() | ForEach-Object ...
```
This PR modifies the powershell scripts to …

Fix powershell scripts for Powershell 5.1.14393

---

manifests/windows/forge-modules.txt
scripts/windows/Init/post-clone-run-once.ps1
scripts/windows/install-win-packages.ps1
scripts/windows/puppet-configure.ps1
templates/windows-2016rtm/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2016rtm/files/windows-2016rtm-x86_64-vmware.package.ps1

This needs associated changes to the puppet-configure script.
The configure scripts changes are useful - the need to revert to PS
1.0.6 is under review.
Need to tidy up version handling using PS splatting but putting this out for review for the moment.
/cc @McdonaldSeanp @glennsarti

(RE-7957) Change Powershell module to 1.0.6

---

manifests/windows/windows_template/manifests/local_group_policies.pp

This commit configures the NTP Client for Windows packer templates to use the
Puppet NTP servers, using local Group Policy settings.
Ref:
https://technet.microsoft.com/en-us/library/Cc773263(v=WS.10).aspx#w2k3tr_times_tools_uhlp
https://technet.microsoft.com/en-us/library/Cc773263(v=WS.10).aspx#w2k3tr_times_tools_vwtt

(RE-8033) Configure NTP Time Synchronisation for Windows guests

---

templates/windows-2012r2/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2016rtm/files/config-vmware-vsphere-cygwin.ps1

Previously the Windows Packer templates were only setting a small number of
Explorer UI settings.  These settings make it a better user experience when
diagnosing issues and also increases the apparent speed of Explorer.  This
commit modifies the Windows Server 2012R2 and 2016 templates to setup Explorer
with the following settings:
- Always show icons, never thumbnails
- Always show menus
- Display file icon on thumbnails
- Display the full path in the title bar
- Show hidden files, folders, and drives
- Show empty drives
- Show extensions for known file types
- Show folder merge conflicts
- Show protected operating system files
- Combine taskbar when full
- Show Administrative Tools on Start Menu
- Do not drag full windows
- Disable font smoothing
- Disable Aero Peek
This commit also …

(maint) Modify default Windows Explorer UI for Windows templates

---

scripts/windows/install-win-packages.ps1
scripts/windows/windows-env.ps1
templates/windows-2012r2/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2016rtm/files/config-vmware-vsphere-cygwin.ps1

This allows us to share the function across both current windows/json
templates and the windows installer powershell script.
Update the windows install (EULA Accept) to use new function.
This is a follow on from @glennsarti PR #128

(MAINT) Move Set-User-Key function to windows-env

---

manifests/modules/packer/manifests/puppet.pp

Soon we will be changing out the key used to sign the new public repos.
This code will break once that happens without this update, but this
update should be merged as close as possible to when the repos are
switched over to the new key

(RE-8013) Update to use new signing key

---

scripts/windows/clean-disk-dism.ps1
templates/windows-2012/files/autounattend.xml
templates/windows-2012/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2012/files/generalize-packer.autounattend.xml
templates/windows-2012/files/win-2012-x86_64-std.pp
templates/windows-2012/files/windows-2012-x86_64-vmware.package.ps1
templates/windows-2012/x86_64.vmware.base.json
templates/windows-2012/x86_64.vmware.vsphere.cygwin.json

Initial load of Win-2012 files for base win-2012 build.
This is mostly a copy of the win-2012r2 template with the following main changes:
1. DISM command for 2012 doesn't support /resetbase (leads to larger image unfortunately).
2. Initial image size needs to be 30GB
Remainder of template code appears to operate satisfactorily.

(IMAGES-48) Packer Windows-2012 Automation

---

templates/windows-2012/x86_64.vmware.base.json

This is a first pass at a slipstreamed .iso for the Win-2012 build
It reduces the number of updates to about 80 rather than 260, thus
reducing the overall Windows Update time during build from about 10
hours to 2 hours.

(IMAGES-331) Use Slipstream ISO for Windows 2012

---

util/windows/win-2012/win-2012-slipstream.ps1

The Win-2012 slipstream was produced manually - this is a save of the
main batch/powershell commands that were used to create it.
This will be used as a basis to script a better solution for future
slipstream work.

(MAINT) Save Win-2012 slipstream commands

---

scripts/windows/cleanup-host.ps1
scripts/windows/init/post-clone-configuration.ps1
scripts/windows/init/vmpooler-clone-arm-runonce.reg
scripts/windows/windows-env.ps1
templates/windows-2012/files/post-clone.autounattend.xml
templates/windows-2012/x86_64.vmware.base.json
templates/windows-2012/x86_64.vmware.vsphere.cygwin.json
templates/windows-2012r2/files/post-clone.autounattend.xml
templates/windows-2012r2/x86_64.vmware.base.json
templates/windows-2012r2/x86_64.vmware.vsphere.cygwin.json
templates/windows-2016rtm/files/post-clone.autounattend.xml
templates/windows-2016rtm/x86_64.vmware.base.json
templates/windows-2016rtm/x86_64.vmware.vsphere.cygwin.json

The Run Once key in the registry is armed to execute a sysprep command
which runs the sysprep and then the post-clone configuration script.
Add unattended file for all current OS along with an update to the
vsphere json file to upload the unattended file
Removed HKCU registry key configuration to since Default User keys will
now be used to create the Administrator Profile after the sysprep.
Needed to add one registry fix to the post-clone-config to correct the
background screen setting.

(IMAGES-76) Change Post-Clone to sysprep operation

---

manifests/windows/windows_group_policy/templates/local_gpo.ps1
templates/windows-2008r2/README.md
templates/windows-2008r2/files/autounattend.xml
templates/windows-2008r2/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2008r2/files/generalize-packer.autounattend.xml
templates/windows-2008r2/files/post-clone.autounattend.xml
templates/windows-2008r2/files/win-2008r2-x86_64-std.pp
templates/windows-2008r2/files/windows-2008r2-x86_64-vmware.package.ps1
templates/windows-2008r2/x86_64.vmware.base.json
templates/windows-2008r2/x86_64.vmware.vsphere.cygwin.json

The files and procedures needed to create the Win-2008r2 template for
packer.
Note - some incompatible scripts (e.g. disk sizing) have been exluded in
this commit and will be handled later.
Modifications were also required to the Policy editor script to handle
PS Version 2

(IMAGES-7832) Add Win-2008R2 Base and Cygwin Templates to packer

---

scripts/windows/generate-slipstream.ps1
scripts/windows/slipstream.package.ps1
templates/windows-2012r2/files/slipstream-filter
templates/windows-2012r2/x86_64.vmware.base.json
templates/windows-2012r2/x86_64.vmware.slipstream.json

Specialised template that:
1. Boots from base Windows ISO
2. Downloads and installs all windows updates from a WSUS Server.
3. Applies the updates to an offline copy of the windows image.
4. Generates a new ISO Slipstream image from the offline updated copy.
This image can then be exported to ```osmirror``` to be used for the Packer/Windows build process.
It is intended for manual use on a desktop at the moment.

(IMAGES-369) Special template for slipstream

---

templates/windows-10/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2008r2/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2012/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2012r2/files/config-vmware-vsphere-cygwin.ps1
templates/windows-7/files/config-vmware-vsphere-cygwin.ps1
templates/windows-8.1/files/config-vmware-vsphere-cygwin.ps1

The Autologon registry changes were removed, but the replacement
sysinternals autologon utility wasn't added for all OS's prior to
Win-2016. This means that the Windows Images don't initialise on the
pooler.

(IMAGES-389) Re-Enable autologin for first boot

---

templates/windows-2012r2-ja/README.md
templates/windows-2012r2-ja/files/autounattend.xml
templates/windows-2012r2-ja/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2012r2-ja/files/generalize-packer.autounattend.xml
templates/windows-2012r2-ja/files/post-clone.autounattend.xml
templates/windows-2012r2-ja/files/slipstream-filter
templates/windows-2012r2-ja/files/win-2012r2-x86_64-std.pp
templates/windows-2012r2-ja/files/windows-2012r2-ja-x86_64-vmware.package.ps1
templates/windows-2012r2-ja/files/windows-ja-slipstream.package.ps1
templates/windows-2012r2-ja/x86_64.vmware.base.json
templates/windows-2012r2-ja/x86_64.vmware.slipstream.json
templates/windows-2012r2-ja/x86_64.vmware.vsphere.cygwin.json

Add build for Japanese Windows-2012R2.
This is deliberately using the Copy/Pasta approach, i.e. making a full
copy of the template files for English-Win-2012R2.
A further ticket will look to combining the templates once the
complexities of a localised build have been evaluated.

(IMAGES-336) Create Japanese template

---

scripts/windows/init/post-clone-configuration.ps1
templates/windows-2008r2/files/post-clone.autounattend.xml
templates/windows-7/files/post-clone.autounattend.xml
templates/windows-8.1/files/post-clone.autounattend.xml

The Windows-2008r2, Windows-8.1 and Windows-7 Post-Clone sysprep
unattended.xml files were missing specialisation phase, specifically the
hostname which was causing the post-clone operation to fail.
Windows 7/2008r2 and earlier also don't use the Rename-Computer cmdlet
so we need alternative code for this.

(IMAGES-391) Correct Post-Clone sysrep spec

---

scripts/windows/generate-slipstream.ps1
scripts/windows/init/post-clone-configuration.ps1
templates/windows-10/README.md
templates/windows-10/files/post-clone.autounattend.xml
templates/windows-10/files/slipstream-filter
templates/windows-10/files/windows-10-slipstream.package.ps1
templates/windows-10/x86_64.vmware.slipstream.json
templates/windows-10/x86_64.vmware.vsphere.cygwin.json

Use Slipstream image to prepare ISO with the latest CU available. This
reduces the overall install time, but may need to be updated prior to
each release to include the latest CU.
The DISM cleanup is done as part of the slipstream process so the
clean-dism script is not used for Windows-10 base build - at least until
bare-metal hardware is introduced as otherwise the jenkins-imaging
builds fail fairly consistently.

(IMAGES-22) Address DISM issues in Win-10 template

---

templates/ubuntu-16.10/i386.virtualbox.base.json
templates/ubuntu-16.10/x86_64.virtualbox.base.json

We need to ensure that the variables section of the definition contains
a reference to the user section key headless.

(maint) Yakkety Virtualbox VMs should be headless

---

manifests/modules/packer/manifests/updates.pp
templates/ubuntu-16.10/CHANGELOG
templates/ubuntu-16.10/i386.vsphere.nocm.json
templates/ubuntu-16.10/x86_64.vsphere.nocm.json

periodic apt updates can lead to dpkg being locked at inconvenient times

(maint) disable periodic updates on ubuntu

---

manifests/modules/packer/manifests/updates.pp

the kernel package is required to be updated at install time so it matches the kernel-devel version, required for VBoxGuestAddtions installation

(CPR-395) Update kernel package with osfamily RedHat

---

.travis.yml

Update travis to use the trusty container rather than the default of
precise.  This will address an issue with the old curl in precise and
newly issued hashicorp certs.
Related to https://github.com/travis-ci/travis-ci/issues/7131

(maint) update travis to use trusty

---

scripts/windows/clean-disk-dism.ps1
scripts/windows/clean-disk-sdelete.ps1
scripts/windows/cleanup-host.ps1
scripts/windows/windows-env.ps1
templates/windows-10/files/i386/windows-10-i386-vmware.package.ps1
templates/windows-10/files/i386/windows-10-slipstream.package.ps1
templates/windows-10/files/x86_64/windows-10-slipstream.package.ps1
templates/windows-10/files/x86_64/windows-10-x86_64-vmware.package.ps1
templates/windows-10/i386.vmware.base.json
templates/windows-10/x86_64.vmware.base.json
templates/windows-2008r2/files/windows-2008r2-x86_64-vmware.package.ps1
templates/windows-2012/files/windows-2012-x86_64-vmware.package.ps1
templates/windows-2012r2-ja/files/windows-2012r2-ja-x86_64-vmware.package.ps1
templates/windows-2012r2-ja/files/windows-ja-slipstream.package.ps1
templates/windows-2012r2/files/virtualbox/windows-2012r2-x86_64-virtualbox.package.ps1
templates/windows-2012r2/files/vmware/windows-2012r2-x86_64-vmware.package.ps1
templates/windows-2012r2/x86_64.virtualbox.base.json
templates/windows-2012r2/x86_64.vmware.vsphere.cygwin.json
templates/windows-2016/files/windows-2016-x86_64-vmware.package.ps1
templates/windows-7/files/windows-7-slipstream.package.ps1
templates/windows-7/files/windows-7-x86_64-vmware.package.ps1
templates/windows-8.1/files/windows-8.1-x86_64-vmware.package.ps1

This corrects two issues were causing failures to the Image builder:
1. System goes to sleep during long update cycles (esp win-10/2016)
(This was already tested for win-10 and is being rolled out to all builds).
This also affected the Dism Cleanup operations which had to be removed.
2. Windows Update could occur during subsequent configuration stages,
especially if the base image was built over a month previously.
Again Win-10/2016 were impacted the most due to the size of the
Cumulative Update downloaded each month.
Since no further updates should be done to the image once the base is
done, the Download cache for Windows Update is also cleaned.

(IMAGES-439) Windows Update Fixes

---

scripts/windows/clean-disk-dism.ps1
scripts/windows/generate-slipstream.ps1
scripts/windows/windows-env.ps1
templates/windows-2012/files/slipstream-filter
templates/windows-2012/files/windows-2012-slipstream.package.ps1
templates/windows-2012/files/windows-2012-x86_64-vmware.package.ps1
templates/windows-2012/x86_64.vmware.slipstream.json

The Windows-2012 build hangs indefinately during the Windows Update.
The first step to address this was to create a formal slipstream build
process for Win-2012 (as the first slipstream was built manually) and to
ensure that all the correct Windows Servicing Stack updates were
installed correctly to allow it to operate with WSUS.
It was also necessary to filter out a number of updates during the DISM
offline servicing phase as these appeared to corrupt the image. Three of
the updates are critical however, to the actual build, so these are
inserted into the main build package script just prior to the windows
update phase.

(IMAGES-385) Resolve Win-2012 build hang

---

templates/windows-10/i386.vmware.base.json
templates/windows-10/i386.vmware.slipstream.json
templates/windows-10/i386.vmware.vsphere.cygwin.json
templates/windows-10/x86_64.vmware.base.json
templates/windows-10/x86_64.vmware.slipstream.json
templates/windows-10/x86_64.vmware.vsphere.cygwin.json
templates/windows-2008r2/x86_64.vmware.base.json
templates/windows-2008r2/x86_64.vmware.vsphere.cygwin.json
templates/windows-2012/x86_64.vmware.base.json
templates/windows-2012/x86_64.vmware.vsphere.cygwin.json
templates/windows-2012r2-ja/x86_64.vmware.base.json
templates/windows-2012r2-ja/x86_64.vmware.vsphere.cygwin.json
templates/windows-2012r2/x86_64.virtualbox.base.json
templates/windows-2012r2/x86_64.virtualbox.vagrant.cygwin.json
templates/windows-2012r2/x86_64.vmware.base.json
templates/windows-2012r2/x86_64.vmware.vsphere.cygwin.json
templates/windows-2016/x86_64.vmware.base.json
templates/windows-2016/x86_64.vmware.vsphere.cygwin.json
templates/windows-7/x86_64.vmware.base.json
templates/windows-7/x86_64.vmware.vsphere.cygwin.json
templates/windows-8.1/x86_64.vmware.base.json
templates/windows-8.1/x86_64.vmware.vsphere.cygwin.json

This is to support the updated jenkins/jjb job structure and using Git specifications in the build.
It also updates the Input/Output directories for all the Windows/Packer builds to remove Hypervisor (VMWARE) specific dents and to support the vagrant builds on ```jenkins-imaging```

(IMAGES-376) Revised In/Out VMWare Directories

---

scripts/windows/init/vagrant-arm-host.ps1
scripts/windows/init/vmpooler-post-clone-configuration.ps1
templates/windows-2012r2/x86_64.virtualbox.vagrant.cygwin.json

This corrects the issue where sshd can't create a proper token
when using ssh public key authentication. This is documented in
https://cygwin.com/cygwin-ug-net/ntsec.html#ntsec-nopasswd1.

(IMAGES-480) Enable LSA for Cygwin Authentication

---

scripts/windows/cleanup-host.ps1
templates/windows-2008r2-wmf5/README.md
templates/windows-2008r2-wmf5/files/autounattend.xml
templates/windows-2008r2-wmf5/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2008r2-wmf5/files/generalize-packer.autounattend.xml
templates/windows-2008r2-wmf5/files/post-clone.autounattend.xml
templates/windows-2008r2-wmf5/files/win-2008r2-x86_64-std.pp
templates/windows-2008r2-wmf5/files/windows-2008r2-wmf5-x86_64-vmware-base.package.ps1
templates/windows-2008r2-wmf5/x86_64.vmware.base.json
templates/windows-2008r2-wmf5/x86_64.vmware.vsphere.cygwin.json
templates/windows-2008r2/README.md
templates/windows-2008r2/x86_64.vmware.vsphere.cygwin.json
templates/windows-2012r2-ja/README.md
templates/windows-2012r2-wmf5/README.md
templates/windows-2012r2-wmf5/files/config-winsettings.ps1
templates/windows-2012r2-wmf5/files/slipstream-filter
templates/windows-2012r2-wmf5/files/vmware/autounattend.xml
templates/windows-2012r2-wmf5/files/vmware/generalize-packer.autounattend.xml
templates/windows-2012r2-wmf5/files/vmware/post-clone.autounattend.xml
templates/windows-2012r2-wmf5/files/vmware/windows-2012r2-wmf5-x86_64-vmware-base.package.ps1
templates/windows-2012r2-wmf5/files/win-2012r2-x86_64-std.pp
templates/windows-2012r2-wmf5/x86_64.vmware.base.json
templates/windows-2012r2-wmf5/x86_64.vmware.vsphere.cygwin.json

Add WMF5 templates for Windows 2008R2 and 2012R2.
This PR has 3 commits:
1. Windows-2008r2 WMF 5 Template (IMAGES-422)
2. Windows-2012r2 WMF 5 Template (IMAGES-423)
3. Maint changes to Readme files and a title (Windows Edition was incorrect).
A new WMF5 base template was required for both of these OS's as the WinRM interface that Packer uses for the post-configuration is unable to update WMF without several workarounds. This approach also ensures that any Windows updates appropriate to the WMF patch are also included in the build.

(IMAGES-423) WMF5 templates for Win-2012r2/2008r2

---

manifests/modules/packer/manifests/vsphere/repos.pp
templates/ubuntu-16.10/i386.vmware.vsphere.nocm.json
templates/ubuntu-16.10/x86_64.vmware.vsphere.nocm.json

Due to yakkety including a puppet-agent package, we need to pin to
ensure apt prefers out AIO package.

(maint) address upstream packaging issue on yakkety

---

manifests/modules/packer/manifests/vmtools.pp
manifests/modules/packer/manifests/vsphere/networking.pp
manifests/modules/packer/templates/vsphere/redhat.rb.erb
templates/centos-7.2/x86_64.vmware.base.json
templates/centos-7.2/x86_64.vmware.vsphere.nocm.json

The related bits around building CentOS 7 for use with the vmpooler have not been updated in ages and requires some modifications.
- Use open-vm-tools instead of installing from the tools ISO.
- Use vmxnet3 for vSphere artificats
- vmpooler bootstrap and config file fixups due to networking changes
- Switch to the AIO method for provisioning.
I'm still waiting to get a build through jenkins-imaging, but a local build appears to behave as expected.
```shell
[root@c3f8ab4jpwyhwpg tmp]# cat vsphere-bootstrap.log
Nice to meet you, my VM name is 'c3f8ab4jpwyhwpg'.
- Setting local hostname...
- Re-obtaining DHCP lease...
Redirecting to /bin/systemctl restart  NetworkManager.service
Device 'ens160' successfully disconnected.
Connection successfully activated (D-Bus active path: …
```

(maint) centos7 vsphere fixups

---

scripts/windows/clean-disk-dism.ps1
scripts/windows/cleanup-host.ps1
scripts/windows/generate-slipstream.ps1
scripts/windows/init/vmpooler-arm-host.ps1
scripts/windows/init/vmpooler-post-clone-configuration.ps1
scripts/windows/install-cygwin.ps1
scripts/windows/install-win-packages.ps1
scripts/windows/windows-env.ps1
templates/windows-2008/README.md
templates/windows-2008/files/autounattend.xml
templates/windows-2008/files/config-vmware-vsphere-cygwin.ps1
templates/windows-2008/files/generalize-packer.autounattend.xml
templates/windows-2008/files/post-clone.autounattend.xml
templates/windows-2008/files/shutdown-packer-2008.ps1
templates/windows-2008/files/win-2008-x86_64-std.pp
templates/windows-2008/files/windows-2008-slipstream.package.ps1
templates/windows-2008/files/windows-2008-x86_64-vmware-base.package.ps1
templates/windows-2008/x86_64.vmware.base.json
templates/windows-2008/x86_64.vmware.slipstream.json
templates/windows-2008/x86_64.vmware.vsphere.cygwin.json
util/windows/win-2008/win-2008-slipstream.ps1

Create the base and vSphere templates for Windows-2008
This packer build differs a bit from the other windows:
1. Slipstream had to be prepared manually in a few stages due to the
necessity of adding Powershell, .Net 3.5 SP1 and .Net 4.5.2 before
boxstarter could be used to collect the updates. Further DISM
is not available yet for Win-2008, so the actual .iso build and
offline servicing had to be done on a Windows-2012R2 machine.
2. The base build assumes Powershell has been injected into the image
through the slipstream process which allows boxstarter to start
and automatically pull in the final set of required updates.
3. Powershell scripts need to be run elevated explicitly - this is
probably due to the UAC model for Vista/2008 SP2. But it also means
a nasty workaround has to be …

(IMAGES-39) Add Windows-2008 Template

---

.gitignore

Think this was introduced while adding tests.  
manifests/modules/packer/* was also ignores, which seems not correct.

corrects faulty ignore of packer manifests files

---

manifests/modules/packer/manifests/updates.pp
manifests/modules/packer/templates/vsphere/sles.rb.erb
templates/sles-12.1/files/sles-12-sp1-x86_64-autoinst.xml
templates/sles-12.1/x86_64.vmware.base.json
templates/sles-12.1/x86_64.vmware.vsphere.nocm.json
templates/sles-12.2/files/sles-12-sp2-x86_64-autoinst.xml
templates/sles-12.2/x86_64.vmware.vsphere.nocm.json

This adds a step to make sure sles isn't adding locks to packages and updates the template names to be consistent between sp1 and sp2

Updates for SLES-12 sp1 and sp2 builds

---

manifests/windows/windows_template/manifests/configure_services.pp
scripts/windows/cleanup-host.ps1
scripts/windows/install-cygwin.ps1
scripts/windows/start-boxstarter.ps1
scripts/windows/windows-env.ps1
templates/windows-2008/files/x86_64/vmware/windows-2008-x86_64-vmware-base.package.ps1
templates/windows-2008/files/x86_64/windows-2008-slipstream.package.ps1
templates/windows-2008/x86_64.vmware.base.json
templates/windows-2008r2-wmf5/files/x86_64/vmware/windows-2008r2-wmf5-x86_64-vmware-base.package.ps1
templates/windows-2008r2/files/slipstream-filter
templates/windows-2008r2/files/x86_64/vmware/windows-2008r2-x86_64-vmware-base.package.ps1
templates/windows-2008r2/files/x86_64/windows-2008r2-slipstream.package.ps1
templates/windows-2008r2/x86_64.vmware.base.json
templates/windows-2008r2/x86_64.vmware.slipstream.json
templates/windows-2012/files/x86_64/windows-2012-slipstream.package.ps1
templates/windows-2012/x86_64.vmware.base.json
templates/windows-2012r2-wmf5/x86_64.vmware.base.json
templates/windows-2012r2/x86_64.virtualbox.base.json
templates/windows-2012r2/x86_64.vmware.base.json
templates/windows-7/files/x86_64/vmware/windows-7-x86_64-vmware-base.package.ps1
templates/windows-7/files/x86_64/windows-7-slipstream.package.ps1
templates/windows-7/x86_64.vmware.slipstream.json

Fix instability issues in early Windows builds (Win-2008 -> Win-2012).
Most of the instability was caused by two issues:
1. Boxstarter Update which broke Win-2008.
2. Chocolatey failure to install .Net 4.5.1 which impacted 2008, 2008r2, 2012 & 7.
This PR also includes fixes for some other issues including:
- Occasional build script failures (e.g. unzip in cygwin install, chocolatey cleanup).
- Google Update Services causing PendingFile Change reboot in vmpooler image.
- Automated and refreshed Slipstreams for Win-2008r2 and Win-2012r2

(IMAGES-546) Address Win-2008 -> Win-2012 Build Stability Issues

---

manifests/windows/windows_template/manifests/configure_services.pp
scripts/windows/windows-env.ps1
templates/windows-10/files/i386/vmware/windows-10-i386-vmware-base.package.ps1
templates/windows-10/files/i386/windows-10-slipstream.package.ps1
templates/windows-10/files/x86_64/vmware/windows-10-x86_64-vmware-base.package.ps1
templates/windows-10/files/x86_64/windows-10-slipstream.package.ps1
templates/windows-10/i386.vmware.slipstream.json
templates/windows-10/x86_64.vmware.slipstream.json
templates/windows-2008r2-wmf5/files/x86_64/vmware/windows-2008r2-wmf5-x86_64-vmware-base.package.ps1
templates/windows-2008r2/files/x86_64/vmware/windows-2008r2-x86_64-vmware-base.package.ps1
templates/windows-2008r2/files/x86_64/windows-2008r2-slipstream.package.ps1
templates/windows-2012/files/x86_64/vmware/windows-2012-x86_64-vmware-base.package.ps1
templates/windows-2012/files/x86_64/windows-2012-slipstream.package.ps1
templates/windows-2012r2-ja/files/x86_64/virtualbox/windows-2012r2-ja-x86_64-virtualbox-base.package.ps1
templates/windows-2012r2-ja/files/x86_64/vmware/windows-2012r2-ja-x86_64-vmware-base.package.ps1
templates/windows-2012r2-ja/files/x86_64/windows-ja-slipstream.package.ps1
templates/windows-2012r2-wmf5/files/x86_64/vmware/windows-2012r2-wmf5-x86_64-vmware-base.package.ps1
templates/windows-2012r2/files/x86_64/virtualbox/windows-2012r2-x86_64-virtualbox-base.package.ps1
templates/windows-2012r2/files/x86_64/vmware/windows-2012r2-x86_64-vmware-base.package.ps1
templates/windows-2016/files/slipstream-filter
templates/windows-2016/files/x86_64/vmware/windows-2016-x86_64-vmware-base.package.ps1
templates/windows-2016/files/x86_64/windows-2016-slipstream.package.ps1
templates/windows-2016/x86_64.vmware.slipstream.json
templates/windows-7/files/x86_64/vmware/windows-7-x86_64-vmware-base.package.ps1
templates/windows-7/files/x86_64/windows-7-slipstream.package.ps1
templates/windows-8.1/files/x86_64/vmware/windows-8.1-x86_64-vmware-base.package.ps1

Add in the automation files for Win-2016 slipstream generation.
The CU for Win-2016 updates has become a bit flaky, so regen the
slipstream to help this.
Also change all .Net 4.5.2 installs to use a more up to date chocolatey package.

(IMAGES-447) Win-2016 Slipstream Automation 

---

templates/debian-9.0/i386.vmware.base.json
templates/debian-9.0/i386.vmware.vsphere.nocm.json
templates/debian-9.0/new_os_hacks/add_libreadline6.sh
templates/debian-9.0/new_os_hacks/remove_libreadline6.sh
templates/debian-9.0/x86_64.vmware.base.json
templates/debian-9.0/x86_64.vmware.vsphere.nocm.json

This commit adds the released stable debian 9 images, and adds a hack to
install jessie libreadline6 packages so the debian jessie agent works on
9 (and we can subsequently use it to provision the VM).
When we release the official version of the debian 9 agent, this hack should
be removed

(IMAGES-569) Update debian 9 image to released version, add hack

---

templates/debian-9.0/i386.vmware.base.json
templates/debian-9.0/i386.vmware.vsphere.nocm.json
templates/debian-9.0/new_os_hacks/add_libreadline6.sh
templates/debian-9.0/new_os_hacks/remove_libreadline6.sh
templates/debian-9.0/x86_64.vmware.base.json
templates/debian-9.0/x86_64.vmware.vsphere.nocm.json

This commit removes the hack we used to get debian 9 to work by using the
newly released agent 1.10.6 for debian 9

(IMAGES-595) Remove debian 9 libreadline hack

---

manifests/modules/packer/manifests/vsphere/repos.pp
templates/fedora-26/x86_64.vmware.base.json
templates/fedora-26/x86_64.vmware.vsphere.nocm.json

This commit does 2 things:
1) Updates several parts of the packer configuration that were outdated and
causing problems in the imaging pipeline
2) Updates the puppet manifests for fedora packages to correctly use fedora26
instead of fedora-26 in the URL for mirrored repos

(IMAGES-592) Update configuration, repos for fedora 26

---

templates/fedora-26/x86_64.vmware.vsphere.nocm.json

the 'beakerhost' variable defines what string to give beaker-hostgenerator to
produce the configuration for this platform. This commit updates the fedora26
config to include that var

(IMAGES-594) Add 'beakerhost' to fedora 26 vsphere image

---

scripts/windows/windows-env.ps1
templates/win-common/files/PostCloneTemplate.xml
templates/win-common/vmware.base.json
templates/win-common/vmware.vsphere.cygwin.json
templates/windows-10/files/i386/platform-packages.ps1
templates/windows-10/files/x86_64/platform-packages.ps1
templates/windows-2008/x86_64.vmware.vsphere.cygwin.json
templates/windows-8.1/files/x86_64/platform-packages.ps1

The Win-2008 .json file for vsphere.cygwin diverges too much from the
rest of the Windows platforms, so an exception is being made for the
stage 2 build. The base build appears to work ok with the generic .json spec.
Also add the following fixes:
1. IMAGES-647 - Fix winrm issue for Powershell 2 based platforms.
2. Remove Store/App packages for Win-8.1 to resolve Sysprep issue

(IMAGES-640) Custom vsphere spec for Win-2008 and other fixes

---

templates/win-2012r2-core/x86_64.vars.json
templates/win-2016-core/x86_64.vars.json

Need a _ instead of - to seperate core for the Beaker Host Generator
Defs for Win-2012r2-core and win-2016-core acceptance tests

(IMAGES-614) Fix BHG Defs for Core

---

manifests/windows/windows_template/manifests/policies/local_group_policies.pp
manifests/windows/windows_template/manifests/registry/machine.pp
manifests/windows/windows_template/manifests/registry/user.pp
scripts/windows/core-shutdown.ps1
templates/win-common/vmware.vsphere.cygwin.json

Remove the Sound/Volume control from the System tray and generally tidy up the Taskbar and System Tray area with a few other small maintenance fixes:
1. Ensure devices.hotplug is set to false for exported VM so that Device Removal Icon is not displayed.
2. Fix an issue with win-2012r2-core and win-2016-core that blocked RunOnce running at post-clone
3. Ensure that Adminstrator can install MSI (IMAGES-599)

(IMAGES-108) Remove Sound from Systray

---

manifests/windows/windows_template/manifests/apps/chrome.pp
manifests/windows/windows_template/manifests/policies/local_group_policies.pp
manifests/windows/windows_template/manifests/registry/machine.pp
scripts/windows/cleanup-host.ps1
scripts/windows/core-shutdown.ps1
scripts/windows/init/vagrant-arm-host.ps1
scripts/windows/init/vmpooler-post-clone-configuration.ps1
scripts/windows/install-win-packages.ps1
scripts/windows/puppet-configure.ps1
scripts/windows/windows-env.ps1
templates/win-2012r2/x86_64.vars.json
templates/win-common/files/AutoUnattendTemplate.xml
templates/win-common/files/Autounattend.xslt
templates/win-common/files/PostCloneTemplate.xml
templates/win-common/files/virtualbox/vagrantfile-windows.template.erb
templates/win-common/gen-xslt.sh
templates/win-common/virtualbox.base.json
templates/win-common/virtualbox.vagrant.cygwin.json

This PR addresses several trailing issues related to the Packer/Windows builds including:
1. Generalising the VagrantFile for vagrant builds (IMAGES-88)
2. Localisation issues for Windows French (IMAGES-335)
3. Windows-7 Post-Clone issues with Vagrant (IMAGES-662)
4. Windows-2012r2 image wasn't setting the image memory size correctly.

(IMAGES-88) Vagrant and Other Packer/Windows Build Cleanup

---

scripts/windows/init/Set-Bginfo.ps1

The "Invoke-Restmethod" isn't available for PS2, so implement in
compatible code that can get the required lifetime and template name.

(IMAGES-455) Fix missing Win-7 BGINFO Data

---

templates/win-common/files/virtualbox/vagrantfile-windows.template.erb
templates/win-common/gen-xslt.sh

The win-2012r2-core vagrant/facter acceptance tests are more due to
incorrect hostname format from the beakerhostgenerator file, but this
opportunity is taken to tidy up the Vagrantfile and its generation, i.e.
the removal of parameters that are not needed etc.

(IMAGES-665) Tidy Vagrantfile parameters

---

scripts/windows/generate-slipstream.ps1
scripts/windows/install-cygwin.ps1
scripts/windows/install-win-packages.ps1
scripts/windows/start-pswindowsupdate.ps1
scripts/windows/windows-env.ps1
templates/win-2008/files/x86_64/platform-packages.ps1
templates/win-2008r2-wmf5/files/x86_64/platform-packages.ps1
templates/win-2012r2-wmf5/files/x86_64/platform-packages.ps1

This change updates references from using http://buildsources.delivery.puppetlabs.net/ to https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/.

(RE-9766) Update puppetlabs-packer to use artifactory

---

tests/test-syntax.sh

With the new directory structure of the templates established,
variable files will be named "vars.json". This would fail Travis
because it expects "vars.json" files to have a prefix, originally
meant for the architecture. This commit fixes Travis to avoid
failure for that case.

(maint) Update Travis to not fail with the new naming convention

---

tests/test-syntax.sh

This should be reverted once everything conforms to the new
directory structure.

(maint) Add back old filter so that CI passes

---

scripts/windows/init/vagrant-arm-host.ps1

Windows-10/2016 insists on creating public network adaptors after a sysprep which means WinRM fails to come up properly (Earlier versions of windows allow you to set the adaptors private in the unattend.xml).
So detect if this Windows-10/2016 and set the adapters private.

(IMAGES-680) Win-10 Needs private network adapters

---

scripts/windows/init/vmpooler-post-clone-configuration.ps1

Small maint change to improve the acceptance reliability.
Starting sshd before we reboot to rename the host causes failures in the
vcloud/beaker hypervisor - suspect this is because it uses IP addresses
rather than the given hostname to detect when the host is alive, thus
breaking the test initialisation sequence. The vmpooler initialisation
is more tolerant of this as it the ssh test uses the given hostname
which isn't active until after the reboot.
Suspect we can further rationalise and tidy the overal ssh startup
sequence (i.e. use Automatic start), but lets just do this for now.

(MAINT) Don't start sshd during post-clone

---

scripts/windows/windows-env.ps1

The "icacls" command was failing after it was localised - fix this and
ensure all permission changes/deletes are logged verbosely so that we
can verify the cleanup is happening (may choose to switch verbose mode
off at a later stage once this is working stably).

(IMAGES-684) Fix File/Directory clean

---

scripts/windows/init/vmpooler-clone-startup.ps1
scripts/windows/init/vmpooler-post-clone-configuration.ps1

The SSHD startup was still happening in a seperate script to the
post-clone operation. This seems to cause a failure for sshd to come up
in the image accpeptance test env.
Simplify this by setting sshd as Automatic as one of the last commands
before the computer is renamed and take the startup out of the
startup-script.
The mkpasswd and mkgroup commands are also copied to the post-clone
operation to ensure these are in place before the first sshd
initialisation.

(IMAGES-707) Set SSHD as Automatic in post-clone

---

manifests/windows/windows_template/manifests/policies/local_group_policies.pp
scripts/windows/init/vmpooler-post-clone-configuration.ps1
templates/win-10-1607/x86_64.vars.json
templates/win-10-ent/i386.vars.json
templates/win-10-ent/x86_64.vars.json
templates/win-10-pro/x86_64.vars.json
templates/win-2008/x86_64.vars.json
templates/win-2008r2-wmf5/x86_64.vars.json
templates/win-2008r2/x86_64.vars.json
templates/win-2012/x86_64.vars.json
templates/win-2012r2-core/x86_64.vars.json
templates/win-2012r2-fr/x86_64.vars.json
templates/win-2012r2-ja/x86_64.vars.json
templates/win-2012r2-wmf5/x86_64.vars.json
templates/win-2012r2/x86_64.vars.json
templates/win-2016-core/x86_64.vars.json
templates/win-2016/x86_64.vars.json
templates/win-7-wmf5/x86_64.vars.json
templates/win-7/x86_64.vars.json
templates/win-81/x86_64.vars.json
templates/win-common/files/Autounattend.xslt

The Timezone setting for the Windows Images wasn't set to UTC.
This was a side effect of fixing a timezone issue for win-7 that
filtered the setting out completely for all images.
Also add in an IP Anycast address for the NTP server as recommended by
IT.

(IMAGES-722) Fix windows image timezones

---

manifests/modules/packer/templates/vsphere/redhat.rb.erb

This was a tweak I had to make to get the redhat fips image to build. Previously we haven't had any official RedHat templates in this repo, only CentOS/Scientific/Oracle.

(maint) Update vsphere setup script to work with official RedHat images

---

templates/win/common/gen-xslt.sh

Fix typo in gen-xslt.sh to pickup windows 32 bit architecture for
autounattend.xml

(IMAGES-721) Fix i386 win architecture

---

templates/win/2008r2/x86_64/vars.json
templates/win/common/google.base.json

First pass at Windows 2008r2 GCE Template.
This is being added as a stub for the moment, as there are some issues
with this method that need to be resolved.
In particular, unable to translate variables in the powershell provider
which has been opened as a packer issue (5878)
There is also the question if we can obtain the winrm_password which is
set using the GCE Api - this will be needed to enable auto-login which
is required for Appveyor
Submitting this in the interim as practice code.

(WIN-73) Initial Win-2008r2 GCE Template

---

manifests/base.pp
manifests/modules/packer/manifests/repos.pp
manifests/modules/packer/manifests/vsphere/repos.pp
templates/common/vmware.vsphere.nocm.json
templates/redhat/6.8/common/files/ks.cfg
templates/redhat/6.8/i386/vars.json
templates/redhat/6.8/x86_64/vars.json
templates/redhat/7.2/common/files/ks.cfg
templates/redhat/7.2/x86_64/vars.json

I think somewhere down the line, the ethernet0 default of vmxnet3 disappeared from the vsphere template. This restores it but in a manner that allows for variable overrides if for some reason a platform doesn't want to use that device (we generally want it used everywhere possible for better networking performance).
It also eliminates the need for using the enable-rhel-repos bootstrap script and puppetizes the configuring of a default yum mirror for RHEL vmware base template installs.I'll finally remove that script after updating the RHEL 7.0-fips template.

RHEL 6.8 and 7.2 Templates and Improvements

---

templates/redhat/7.2-fips/x86_64/vars.json

This just amounts to a version bump, as a rebuild will pick up the new
repo scheme as defined in repos.pp.

(maint) Update redhat-fips 7.2 image to use new mirror repos

---

manifests/modules/packer/manifests/repos.pp
manifests/modules/packer/manifests/vsphere/repos.pp
templates/redhat/6.8/i386/vars.json
templates/redhat/6.8/x86_64/vars.json
templates/redhat/7.2-fips/x86_64/vars.json
templates/redhat/7.2/x86_64/vars.json

Previously I've seen RHEL 6.8 x86_64 kernel panic on boot when imported into vCenter, but the panic isn't reproducible locally. I've built this template locally and uploaded it into vCenter and it actually boots. So I'm wondering if the issue is actually what version of VMWare is used to *build* the template, and if it turns out that building it via the Jenkins imaging pipeline again results in a template that won't boot, I can at least rebuild it locally and upload it from my own host.

RHEL 6.8 Fixes

---

templates/win/2008r2-wmf2/x86_64/vars.json
templates/win/2008r2-wmf3/x86_64/vars.json
templates/win/2008r2-wmf4/x86_64/vars.json
templates/win/2008r2/x86_64/vars.json
templates/win/common/google.appveyor.json

A number of consistency tidy ups to the Google/Appveyor image generation
including:
1. Move 2008R2-WMF4 into its own directory.
2. Remove all other variables from the appveyor defs as they are
appveyor builds only.
3. Add a "comment" variable for clarity.
4. Shorten generated image name (google isn't necessary)

(WIN-77) JJB Related Fixups for Appveyor Image Gen

---

templates/redhat/7.2/x86_64/vars.json

This is a platform we often use for PE master testing and requires 6 GB
of RAM.

(IMAGES-781) Increase RAM for redhat-7-x86_64 to 6 GB

---

manifests/modules/packer/manifests/updates.pp
templates/redhat/6.8/i386/vars.json
templates/redhat/6.8/x86_64/vars.json

This updates the RAM settings to match what is currently used in the
redhat-6 vmpooler templates, and adds a workaround preventing the kernel
pacakge from being upgraded when building the template, to avoid a
kernel panic on bootup.

(maint) Fixes for redhat-6 templates

---

manifests/modules/packer/manifests/vsphere/fw.pp
templates/redhat/6.8/i386/vars.json
templates/redhat/6.8/x86_64/vars.json

During the update from RHEL 6.5 -> 6.8, RedHat enabled a firewall
service by default. We disable this in the redhat-7 template build
process, so do this also for redhat-6.

(IMAGES-783) Disable firewall service for redhat-6 templates

---

manifests/modules/packer/manifests/networking/params.pp
templates/centos/7.4/common/files/ks.cfg
templates/centos/7.4/x86_64/vars.json
templates/centos/common/vars.json
templates/common/docker.nocm.json
templates/common/docker.puppet.json
templates/common/libvirt.base.json
templates/common/libvirt.nocm.json
templates/common/libvirt.puppet.json
templates/common/virtualbox.base.json
templates/common/virtualbox.nocm.json
templates/common/virtualbox.puppet.json

@ScottGarman 
Except for the little modification in the puppet code, everything is separated form the other base code.
I think the naming of the vars I used are subject to changes to follow the naming convention ...
Adds vagrant boxes nocm and puppet for vagrant supporting following hypervisors : 
* libvirt (kvm)
* virtualbox
* docker

Centos 7.4

---

templates/centos/6.8/common/files/ks.cfg
templates/centos/6.8/i386/vars.json
templates/centos/6.8/x86_64/vars.json
templates/centos/README.md

This includes some minor tweaks to the CentOS 6 templates:
* Updated x86_64 template to have 6 GB of RAM
* Updated puppet-agent version to 1.10.10
* Updated README file to explain why we have separate build instructions
for different versions of CentOS

(maint) CentOS 6 updates

---

manifests/modules/packer/manifests/vsphere/repos.pp
templates/scientific/6.8/common/files/ks.cfg
templates/scientific/6.8/i386/vars.json
templates/scientific/6.8/x86_64/vars.json

These images will replace our v6.5 images to address the GitHub TLS
compatibility change.
They build locally and appear to be working with our local mirrors, yum package groups are working, and the firewall is disabled by default.

(IMAGES-739) Add Scientific Linux 6.8 images (i386, x86_64)

---

templates/ubuntu/18.04/common/files/preseed.cfg
templates/ubuntu/18.04/common/vars.json
templates/ubuntu/18.04/x86_64/vars.json

Adds a template for the 18.04 Ubuntu LTS, Bionic Beaver:
- Uses a daily build of the server image for now
- Uses the debian 9 puppet-agent until we can build for this platform
Canoncial will not be distributing an i386 image for 18.04.

(IMAGES-752) Add template for Ubuntu 18.04

---

manifests/modules/packer/manifests/vsphere/repos.pp
templates/centos/6.8/i386/vars.json
templates/centos/6.8/x86_64/vars.json
templates/scientific/6.8/i386/vars.json
templates/scientific/6.8/x86_64/vars.json

The CentOS and Scientific Linux mirror repos do *not* include updates in
their base 'os' repos as was previously assumed. This configures yum to
use separate repos for each of the required os/updates/extras/etc repos,
which differ depending on the distro. I've deliberately kept the
configuration branches separate and self-contained for readability,
given how confusing this has been.

(PE-23924) Fixes for CentOS/Scientific Linux 6 repo configurations

---

manifests/modules/packer/templates/vsphere/ubuntu.rb.erb

The `service` command is no longer a valid way to restart networking on
Ubuntu 18.04 - this commit updates the networking restart command in the
vsphere provisioning script template to use the systemd equivalent
instead.

(IMAGES-752) Fix networking restart on Ubuntu 18.04

---

manifests/modules/packer/manifests/vsphere.pp
manifests/modules/packer/manifests/vsphere/params.pp
manifests/modules/packer/templates/vsphere/ubuntu.rb.erb
manifests/modules/packer/templates/vsphere/vsphere.bootstrap.service
templates/ubuntu/18.04/common/files/preseed.cfg

18.04 commits more heavily to systemd than the previous LTS; Update
several parts of the vsphere bootstrap script for 18.04 to rely on
systemd tools:
- Run the bootstrap script via a oneshot vsphere.bootstrap systemd
service instead of via rc.local
- systemd-networkd's DHCP client uses /etc/machine-id to create a client
ID - this value is the same on hosts cloned from the same template, so
regenerate it during bootstrap
- Use systemd-timesyncd instead of NTP
- Use hostnamectl to set the hostname

(IMAGES-752) Ubuntu 18.04 systemd updates

---

manifests/modules/packer/manifests/vsphere.pp
manifests/modules/packer/manifests/vsphere/params.pp
manifests/modules/packer/templates/vsphere/ubuntu.rb.erb

Fixes two annoyances in the Ubuntu 18.04 bootstrap process:
1. Removes the executable bit from the vsphere-bootstrap systemd service file
on Ubuntu 18.04; This worked fine before, but it wrote a few warnings to the
syslog  (service files should not be executable).
2. Removes the `--now` option when disabling the vsphere-bootstrap systemd
service. Since the the bootstrap script disables the service that runs it
as part of normal execution, when the `--now` option is included in the
disable command, the service will be disabled before the script exits; This
puts the system into an ostensiblly "degraded" state, although nothing is
actually broken. The vsphere bootstrap service is a oneshot service, so
there's no harm in waiting for a reboot for it to be fully disabled.
I've tested this in …

(maint) Ubuntu 18.04 bootstrap process fixups

---

templates/sles/12.1/x86_64/vars.json

This brings this platform into line with the RAM we set for other master
platforms in our vmpooler.

(maint) Increase SLES 12 x86_64 vsphere template to 6 GB RAM

---

templates/centos/README.md
templates/common/docker.nocm.json
templates/common/docker.puppet.json
templates/common/libvirt.base.json
templates/common/libvirt.nocm.json
templates/common/libvirt.puppet.json
templates/common/virtualbox.base.json
templates/common/virtualbox.nocm.json
templates/common/virtualbox.puppet.json
templates/common/vmware.base.json
templates/common/vmware.vsphere.nocm.json
templates/debian/README.md
templates/debian/common/vmware.base.json
templates/fedora/README.md
templates/macos/10.12/x86_64/vmware.base.json
templates/macos/10.13/x86_64/vmware.base.json
templates/macos/README.md
templates/macos/common/vmware.vsphere.nocm.json
templates/redhat/README.md
templates/scientific/README.md
templates/sles/README.md
templates/solaris/11.2/common/vmware.base.json
templates/solaris/README.md
templates/ubuntu/README.md
templates/vro/README.md
templates/vro/common/vmware.vsphere.nocm.json

Adds a support_status variable to all templates to indicate whether the template is maintained by Puppet vs. community maintained. It also adds a Support Status section in the various OS README.md files to clarify which OS versions are Puppet maintained vs. community maintained.

Documentation improvements re: support status

---

templates/win/10-1511/x86_64/vars.json
templates/win/10-1607/x86_64/vars.json
templates/win/10-ent/i386/vars.json
templates/win/10-ent/x86_64/vars.json
templates/win/10-pro/x86_64/vars.json
templates/win/2008/x86_64/vars.json
templates/win/2008r2-wmf2/x86_64/vars.json
templates/win/2008r2-wmf3/x86_64/vars.json
templates/win/2008r2-wmf4/x86_64/vars.json
templates/win/2008r2-wmf5/x86_64/vars.json
templates/win/2008r2/x86_64/vars.json
templates/win/2012/x86_64/vars.json
templates/win/2012r2-core/x86_64/vars.json
templates/win/2012r2-fr/x86_64/vars.json
templates/win/2012r2-ja/x86_64/vars.json
templates/win/2012r2-wmf5/x86_64/vars.json
templates/win/2012r2/x86_64/vars.json
templates/win/2016-core/x86_64/vars.json
templates/win/2016/x86_64/vars.json
templates/win/7-wmf5/x86_64/vars.json
templates/win/7/x86_64/vars.json
templates/win/81/x86_64/vars.json
templates/win/common/files/PostCloneTemplate.xml
templates/win/common/puppet/windows_template/manifests/policies/local_group_policies.pp

Catch-all to finish up the May 2018 Patch Tuesday deploy.
1. Add some convenient shortcuts to the toolbar (IMAGES-31) - first attempt, so leaving ticket open.
2. Remove the My People Icon
3. Update Win-10 to Build 1803
4. Final Version setting for this build (to distinguish from any any pre/test builds)

(IMAGES-831) Windows May 2018 Patch Tuesday deploy

---

templates/win/common/files/Autounattend.xslt

Having TaskbarLinks in the post-clone autounattend for win-2008 stops
the sysprep booting correctly, so filter this out.
As noted earlier, further work needs to be done on this ticket, so just
making this change to allow the May 2018 Patch Tuesday builds to
complete.

(IMAGES-31) No TaskbarLinks for Win-2008

---

templates/win/common/scripts/vmpooler/vmpooler-clone-startup.ps1
templates/win/common/scripts/vmpooler/vmpooler-post-clone-configuration.ps1

Need to add a special case for Win-2008R2 WMF5 as although the Get-NetAdapter cmdlet may be present, it is not supported, so filter it out.

(IMAGES-822) Fix Network Adapter error for Win-2008R2 WMF

---

templates/win/10-1511/x86_64/vars.json
templates/win/10-1607/x86_64/vars.json
templates/win/10-1709/x86_64/vars.json
templates/win/10-ent/i386/vars.json
templates/win/10-ent/x86_64/vars.json
templates/win/10-pro/x86_64/vars.json
templates/win/2008/x86_64/vars.json
templates/win/2008r2-wmf2/x86_64/vars.json
templates/win/2008r2-wmf3/x86_64/vars.json
templates/win/2008r2-wmf4/x86_64/vars.json
templates/win/2008r2-wmf5/x86_64/vars.json
templates/win/2008r2/x86_64/vars.json
templates/win/2012/x86_64/vars.json
templates/win/2012r2-core/x86_64/vars.json
templates/win/2012r2-fr/x86_64/vars.json
templates/win/2012r2-ja/x86_64/vars.json
templates/win/2012r2-wmf5/x86_64/vars.json
templates/win/2012r2/x86_64/vars.json
templates/win/2016-core/x86_64/vars.json
templates/win/2016/x86_64/vars.json
templates/win/2019/x86_64/vars.json
templates/win/7-wmf5/x86_64/vars.json
templates/win/7/x86_64/vars.json
templates/win/81/x86_64/vars.json
templates/win/common/scripts/config/fstab
templates/win/common/scripts/provisioners/install-cygwin.ps1

Setting the NOACL flag in the cygwin /etc/fstab to ensure ACL is not
added to any file creates

(IMAGES-825) Set NOACL for all cygwin file creates

---

templates/centos/7.2/x86_64/vars.json

(IMAGES-824) Bump the template version number in vars.json in centos 7.2 to read from the new template that adds the extras repository, allowing installation from Docker CE.

(IMAGES-824) Bump the template version number in vars.json in centos 7.2

---

templates/centos/7.2/x86_64/vars.json

Since this is a platform we use for testing PE masters, bring this
template in line with our other master test platforms by setting the
amount of RAM to 6 GB.

(maint) Bump CentOS 7.2 RAM to 6 GB

---

templates/vro/common/vmware.vsphere.nocm.json

The original template specified the source path for the VRO vmx file
using the same convention for vmware.base images. This was not the right
way to think about building VRO images, because we do not build a base
image. Instead, we download the raw OVA and convert it to its raw VMX
format, slightly modifying its networking config. to use shared instead
of bridged networking.
This commit modifies the vmware.vsphere.nocm template to take in the
path to the raw VMX file via. an environment variable instead, which
also simplifies the CI code for our VRO images.

(IMAGES-834) Use env. var. to specify raw VMX file for VRO images

---

templates/win/common/files/Autounattend.xslt
templates/win/common/files/PostCloneTemplate.xml
templates/win/common/puppet/windows_template/manifests/policies/local_group_policies.pp
templates/win/common/scripts/common/Pin-AppsToTaskBar.ps1
templates/win/common/scripts/config/StartMenuLayout.xml
templates/win/common/scripts/vmpooler/vmpooler-post-clone-configuration.ps1

This PR requires two different methods depending on platform:
1. Windows-10/2016 uses the new StartLayout GPO policy to define taskbar items.
2. Windows-2012r2 and earlier uses a simple script run during the post-clone configuration.
The <TaskBarLinks> elements used in the Post-Clone Autounattend have also been removed as they didn't work reliably.

(IMAGES-31) Pin Powershell and other apps to the taskbar

---

templates/win/10-1511/x86_64/vars.json
templates/win/10-1607/x86_64/vars.json
templates/win/10-1709/x86_64/vars.json
templates/win/10-ent/i386/vars.json
templates/win/10-ent/x86_64/vars.json
templates/win/10-pro/x86_64/vars.json
templates/win/2008/x86_64/vars.json
templates/win/2008r2-wmf2/x86_64/vars.json
templates/win/2008r2-wmf3/x86_64/vars.json
templates/win/2008r2-wmf4/x86_64/vars.json
templates/win/2008r2-wmf5/x86_64/vars.json
templates/win/2008r2/x86_64/vars.json
templates/win/2012/x86_64/vars.json
templates/win/2012r2-core/x86_64/vars.json
templates/win/2012r2-fr/x86_64/vars.json
templates/win/2012r2-ja/x86_64/vars.json
templates/win/2012r2-wmf5/x86_64/vars.json
templates/win/2012r2/x86_64/vars.json
templates/win/2016-core/x86_64/vars.json
templates/win/2016/x86_64/vars.json
templates/win/2019/x86_64/vars.json
templates/win/7-wmf5/x86_64/vars.json
templates/win/7/x86_64/vars.json
templates/win/81/x86_64/vars.json

Looks like the CVE is going to be tagged later today so doing a final
build run to prepare for deployment.

(IMAGES-831) Update version for build run

---

templates/common/vmware.vsphere.nocm.json
templates/macos/README.md
templates/macos/common/vmware.vsphere.nocm.json
templates/vro/common/vmware.vsphere.nocm.json
templates/win/2008/x86_64/vmware.vsphere.cygwin.json
templates/win/common/vmware.vsphere.cygwin.json

With IMAGES-828 merged in, we have now separated the vCenter uploads
from Packer. This commit removes the vSphere post-processor from all the
templates.

(maint) Remove vSphere post-processor

---

templates/win/10-1803/x86_64/vars.json

The template name for this image was incorrect and duplicating
win-10-ent. Correct it to allow the new template to be created.

(MAINT) Fix win-10-1803 template name

---

templates/fedora/28/x86_64/vars.json

This is needed due to a previous change to use the non-development yum
repos.

(maint) Bump Fedora 28 template version

---

templates/win/10-1511/x86_64/vars.json
templates/win/10-1607/x86_64/vars.json
templates/win/10-1709/x86_64/vars.json
templates/win/10-1803/x86_64/vars.json
templates/win/10-ent/i386/vars.json
templates/win/10-ent/x86_64/vars.json
templates/win/10-pro/x86_64/vars.json
templates/win/2008/x86_64/vars.json
templates/win/2008r2-wmf2/x86_64/vars.json
templates/win/2008r2-wmf3/x86_64/vars.json
templates/win/2008r2-wmf4/x86_64/vars.json
templates/win/2008r2-wmf5/x86_64/vars.json
templates/win/2008r2/x86_64/vars.json
templates/win/2012/x86_64/vars.json
templates/win/2012r2-core/x86_64/vars.json
templates/win/2012r2-fr/x86_64/vars.json
templates/win/2012r2-ja/x86_64/vars.json
templates/win/2012r2-wmf5/x86_64/vars.json
templates/win/2012r2/x86_64/vars.json
templates/win/2016-core/x86_64/vars.json
templates/win/2016/x86_64/vars.json
templates/win/2019/x86_64/vars.json
templates/win/7-wmf5/x86_64/vars.json
templates/win/7/x86_64/vars.json
templates/win/81/x86_64/vars.json

Move Windows version on to avoid clash with deployment templates.

(MAINT) Bump version following deploy

---

manifests/modules/packer/manifests/networking/params.pp
templates/centos/7.5/common/files/ks.cfg
templates/centos/7.5/x86_64/vars.json

I looked at the release notes for CentOS 7.5 to confirm any changes that might cause issues.
1. I added the kpti kernel flag so that images are secure by default. I'm not sure if that matters as much for VMs or not.

Adds CentOS 7.5 template

---

templates/win/common/files/AutoUnattendTemplate.xml
templates/win/common/files/Autounattend.xslt

Windows builds earlier than Win-8 (i.e. Win-2008, 2008R2 and 7) need to
use Vista Driver paths for the initial PE phase on vsphere-iso so that
the pvcsci drivers are loaded and the hard drive is visible.
Use similar method to what is used for Platform/firmware selection to
make this choice.
DriverPaths are only needed for the initial autounattend file and not
the post-clone one.

(IMAGES-890) Fix PE Driver Paths for 2008/7 builds

---

templates/win/10-ent/i386/vars.json
templates/win/common/vmware.vcenter.cygwin.json

The vcenter builds hang either shortly after boot, or in windows-10
during the cumulative update. This appears to be the behaviour noted in
https://github.com/jetbrains-infra/packer-builder-vsphere/issues/119 so applying the recommended fix there.
Also added svga parameters to help correct the console connect issues
associated with the above problem.
Also trivial fix for win-10 32bit Guest ID

(MAINT) Update CPU/svga build parameters

---

templates/fedora/28/x86_64/vars.json

We need a new version to run through our CI pipeline to pick up some
fixes that now properly escape setting the root password via environment
variables during the image build.

(IMAGES-905) Bump Fedora 28 template version

---

templates/win/common/gen-xslt.sh
templates/win/common/scripts/common/windows-env.ps1
templates/win/common/vmware.vcenter.cygwin.json

vcenter has been upgraded to 6.7 which has caused some vmx changes
especially to the firmware (EFI) selection.
Updates to allow the windows patch tuesday refresh.

(IMAGES-907) VMX Paramter changes to reflect recent vcenter upgrade

---

templates/win/common/scripts/bootstrap/start-pswindowsupdate.ps1

Having real problems getting windows update for win-2012, so go out to ms update
for this. Takes a while but seems to download a more consistent set of updates.
Need to revisit and parameterise this for later builds, esp. Slipstream.

(IMAGES-898) Switch off WSUS for Win-2012 as well

---

templates/win/common/scripts/common/windows-env.ps1

Prior to this change, the ForcefullyDelete-Path function did not have
a `process` block. This caused a bug such that only the last directory
in a list given to the function via the pipeline was actually processed
and deleted. This change ensures that the full collection of directories
piped to the function are processed and deleted.
Manual testing was done to ensure that any errors encountered deleting
a directory would not cause the function to stop processing the
remaining items in a given collection.

(IMAGES-916) Fix Path Delete Function

---

templates/win/2019-mock/x86_64/files/platform-packages.ps1
templates/win/2019-mock/x86_64/vars.json
templates/win/common/scripts/bootstrap/start-pswindowsupdate.ps1
templates/win/common/scripts/provisioners/clean-disk-dism.ps1
templates/win/common/scripts/provisioners/clean-disk-sdelete.ps1
templates/win/common/scripts/provisioners/cleanup-host.ps1
templates/win/common/scripts/provisioners/puppet-configure.ps1

This is a partial "quick" windows platform build with enough
components, i.e. Cygwin and ssh settings but nothing else to
provide a fast build template for JJB testing.

(IMAGES-915) Add Mock-Platform build for JJB testing

---

templates/win/2008/x86_64/vmware.vcenter.cygwin.json
templates/win/2008r2-wmf5/x86_64/files/platform-packages.ps1
templates/win/7-wmf5/x86_64/files/platform-packages.ps1
templates/win/common/files/AutoUnattendTemplate.xml
templates/win/common/scripts/bootstrap/bootstrap-packerbuild.ps1
templates/win/common/scripts/bootstrap/packer-windows-update.ps1
templates/win/common/scripts/common/windows-env.ps1
templates/win/common/scripts/provisioners/initiate-windows-update.ps1
templates/win/common/scripts/provisioners/test-bootstrap.ps1
templates/win/common/scripts/provisioners/test-windows-update.ps1
templates/win/common/scripts/provisioners/vagrant-arm-host.ps1
templates/win/common/vars.json
templates/win/common/virtualbox.base.json
templates/win/common/virtualbox.slipstream.json
templates/win/common/virtualbox.vagrant.cygwin.json
templates/win/common/vmware.base.json
templates/win/common/vmware.slipstream.json
templates/win/common/vmware.vcenter.cygwin.json

If a failure happens in the bootstrap phase, it won't get notified until
after a very long timeout period (several hours). So minimise the bootstrap
phase to just installing the hypervisor tools/drivers and any other minimal
network operations so that WinRM can be enabled and control passed back to
packer.
The Windows update phase is initiated later in a seperate phase using the
technique successfully used with the Appveyor build, where WinRm is disabled
just before a packer-reboot provider to allow a further reboot cycle. This
cycle is ended by re-enabling WinRM - thus allowing Windows Update to use as
many reboots as needed.
Also - have changed the startup/reboot sequence to use a Scheduled Task on
Startup to continue the sequence across multiple reboots. This has the
added advantage of …

(IMAGES-917) Seperate the bootstrap stage from win update

---

templates/win/common/vars.json
templates/win/common/vmware.vcenter.cygwin.json

Point the builder to use the new "puppet" build of the
packer-build-vsphere-iso plugin (which is deliberately
named as packer-build-vsphere-plugin-iso to disinguish that
we are using a custom puppet built one until such time as
jetbrains release a revised plugin.
Having the new plugin in place means that we can now direct
the firmware for vcenter builds to efi (except for win-2008
of course). The firmware setting is also removed from the
vmx parameters, where it appeared to cause problems with
ovftool and esxi 6.7

(IMAGES-909) Set firmware for vCenter builds to efi

---

manifests/modules/packer/manifests/vsphere/repos.pp

This is needed to pass nocm and to not enter the default statement.

(maint) Add Solaris to bypass default case in repos.pp

---

manifests/modules/packer/manifests/vsphere/networking.pp
manifests/modules/packer/templates/vsphere/rc.local
manifests/modules/packer/templates/vsphere/solaris.rb.erb
templates/solaris/11.4/x86_64/vars.json

If a new addr is created on Solaris 11.4, the DHCP agent tries to get a new lease that might causes a network outage. 
This PR enables the use of the existing addr for the network interface instead of creating a new one.

fix solaris 11.4 dhcp renewal

---

templates/win/common/vmware.vcenter.cygwin.json

Switch back to the standard vsphere packer plugin and see if the
common (and latest) plugin is used.

(MAINT) Standard vsphere plugin

---

templates/win/10-1511/x86_64/vars.json
templates/win/10-1607/x86_64/vars.json
templates/win/2012r2-core/x86_64/vars.json
templates/win/2016-core/x86_64/vars.json
templates/win/common/scripts/acceptance/windows-update/WindowsUpdate.Tests.ps1
templates/win/common/scripts/bootstrap/packer-windows-update.ps1
templates/win/common/scripts/common/windows-env.ps1
templates/win/common/scripts/provisioners/initiate-windows-update.ps1
templates/win/common/vmware.vcenter.cygwin.json

Add Smoke tests to verify that WindowsUpdate has happened including
1. Updates have been installed in the last 12 hours.
2. There are no pending updates.
3. There are no pending reboots
This update also resolves a serious issue with the windows update during the shutdown sequence (Invoke-Reboot) which allowed a second Get-WuInstall to run and interfere with the shutdown sequence.
Some cosmetic changes were also made to the Windows Update scripts associated with this work as well as minor fixes to the Windows Core builders for the ```Server Core``` type.

(IMAGES-974) WindowsUpdate Tests

---

templates/win/2008/x86_64/vars.json
templates/win/2008/x86_64/vmware.vcenter.cygwin.json
templates/win/2016-core/x86_64/vars.json
templates/win/common/scripts/bootstrap/packer-windows-update.ps1
templates/win/common/scripts/common/windows-env.ps1
templates/win/common/scripts/provisioners/initiate-windows-update.ps1

Series of fixes in order to progress this (November) refresh of Windows platforms:
1. IMAGES-985 - Upgrade PsWindowsUpdate for PS3+
2. Fix the Windows 2008 Build to adopt recent Pester additions.
3. Don't install .Net 4.7 for Win-2008r2/Win-7 (PS2 only) and Win-10/2016.

(IMAGES-985) Update PsWindowsUpdate and other fixes

---

templates/win/common/vmware.vcenter.cygwin.json

This is associated with changes in platform-ci-utils where the
host name is no longer needed, or can default to blank.

(IMAGES-896) Remove Build Hostname

---

templates/win/common/scripts/acceptance/bootstrap-packerbuild/OSVersions.Tests.ps1
templates/win/common/scripts/acceptance/bootstrap-packerbuild/PackerDirectories.Tests.ps1
templates/win/common/scripts/acceptance/cygwin/cygwin.Tests.ps1
templates/win/common/scripts/acceptance/platform/DateTime.Tests.ps1
templates/win/common/scripts/acceptance/platform/DirectoryCleanup.Tests.ps1
templates/win/common/scripts/acceptance/platform/Services.Tests.ps1
templates/win/common/scripts/acceptance/winpackages/sysinternals.Tests.ps1
templates/win/common/scripts/acceptance/winpackages/winpackages.Tests.ps1
templates/win/common/scripts/common/test-packerbuild.ps1
templates/win/common/scripts/common/windows-env.ps1
templates/win/common/scripts/provisioners/install-cygwin.ps1
templates/win/common/vars.json
templates/win/common/vmware.vcenter.cygwin.json

Add additional Pester tests to the image build process for:
1. Windows Packages installation tests
2. Cygwin Installation Tests (not possible to test the full cygwin
configuration at this stage as the final config is done during
vmpooler cloner operation.
3. Overall platform tests, and in particular ensure that Puppetlabs
and other directories are cleaned following the removal of
puppet agent so as to leave the image in a clean state ready for
Puppet CI testing in the pooler.
Some additional tests (e.g. Network/Security) still to be added.

(IMAGES-975) Add Platform Verification Tests

---

templates/common/vmware.base.json

Without this variable, any Linux images built from the top-level
vmware.base.json template will error in the vmtools setup step because
the linux.iso file will not be uploaded onto the image.

(maint) Set tools_upload_flavor to linux in top-level vmware.base.json

---

templates/win/common/vmware.vcenter.cygwin.json

Version 2.3 of the vsphere-iso packer plugin adds a Notes field
which populates the notes field with the relevant build data.
It also supports the -force option, so allows a rebuild on an
an existing VM, which again is useful in development builds.

(IMAGES-957) Add VM Notes Field

---

templates/win/common/puppet/windows_group_policy/manifests/gpupdate.pp
templates/win/common/puppet/windows_group_policy/manifests/local/machine.pp
templates/win/common/puppet/windows_group_policy/manifests/local/user.pp
templates/win/common/puppet/windows_template/manifests/apps/chrome.pp

The validate_re helper function is deprecated, so use Puppet 4 types with
validation instead.
Also remove the mode setting from the google config file as this causes an
issue with Win-10 Build 1809 - the recommendation is to the acl anyways for
permission settings.

(IMAGES-1001) Kill Pupper 3 deprecations

---

manifests/modules/packer/manifests/repos.pp
manifests/modules/packer/manifests/vsphere/repos.pp

This updates the RHEL 6 images to use the artifactory RHEL mirrors.
This also removes configuration of the `lb` repo as our subscription seems to not have access to that. Working to figure out if this is OK for haproxy module testing. If we need to re-add it it can probably happen in a separate PR, the existing cache of the lb repo seems to have very recently expired/corrupted so we can't install any packages from there currently anyways.

(RE-11841) Update RHEL6 mirrors

---

templates/win/common/puppet/windows_template/manifests/apps/powershell6.pp
templates/win/common/scripts/acceptance/puppet/winpackages.Tests.ps1
templates/win/common/scripts/config/win-site.pp
templates/win/common/scripts/provisioners/puppet-configure.ps1
templates/win/common/vars.json

Add Powershell 6 (Core) to the Windows Templates.
WMF 4.0 is a minimum requirement for the Powershell Core installer, so suppress the installation for windows platforms with WMF 2.0 and 3.0

(IMAGES-952) Add Powershell 6

---

templates/win/common/scripts/acceptance/platform/DateTime.Tests.ps1
templates/win/common/scripts/common/windows-env.ps1

French uses a different timezone title in the systeminfo output so add
localisation support to enable Pester tests to work correctly.

(IMAGES-1017) Localise TZ Test

---

templates/redhat/7.2/x86_64/vars.json

This is needed to pick up the recent repo configuration changes for this
platform.

(maint) Bump the RHEL 7 template version

---

manifests/modules/packer/manifests/repos.pp
templates/redhat/7.2-fips/x86_64/vars.json
templates/redhat/7.2/x86_64/vars.json

Artifactory does not merge yum groups in a virtual repo (https://www.jfrog.com/jira/browse/RTFACT-14058), this PR breaks out the os, extras and optional repos to individual yum configs so the systems can use yum groups.

Split out yum repos for rhel 7 for yum group support

---

templates/win/common/scripts/platform9/platform9-config.ps1
templates/win/common/vars.json
templates/win/common/vmware.vcenter.base.json
templates/win/common/vmware.vcenter.platform9.json

Create two separate vcenter build files initially for Platform9. 
Although platform9 is a bios build, the base file should be generic enough to build either UEFI or BIOS files (little packer difference between them once the disk format is setup in the autounattend.xml file).
The base file creates an up to date windows base image, whereas the platform9 file performs the necessary base configuration. Further work will be done in later tickets to add the correct drivers and sysprep stage for platform9.
Provide placeholder platform9 script file to verify the build.

(IMAGES-1004) Platform9 BIOS Base Build

---

manifests/modules/packer/manifests/updates.pp
templates/common/vmware.vcenter.json
templates/ubuntu/18.04/common/files/preseed.cfg
templates/ubuntu/18.04/x86_64/vars.json

Changes:
- Merged base and nocm templates as it is redundant to have 2 build steps on the linux workflow
- Added variables to support windows builds pending unification of this workflow with the windows workflow.

(IMAGES-1016) Linux template for vcenter builds

---

templates/win/2019-mock/x86_64/vars.json
templates/win/common/gen-xslt.sh
templates/win/common/vmware.vcenter.base.json
templates/win/common/vmware.vcenter.cygwin.json
templates/win/common/vmware.vcenter.platform9.json

Use the new packer array variables to vary the valid_exit codes from the
default fail for acceptance tests for the Mock build. This allows the
windows update validation (and other Pester tests) to fail gracefully
without aborting the build.
The Mock build is a very useful build for pipeline througput testing
with a shortened build cycle.
**Breaking** Have also fixed a late-breaking error with the firmware settings that was affecting general windows builds.

(MAINT) Allow Mock build to Fail Gracefully

---

templates/win/common/scripts/common/init-sysprep.ps1

This command is missing a critical space which barfs the sysprep.

(MAINT) Fix /mode:vm for sysprep

---

templates/common/vmware.vcenter.json
templates/common/vmware.vsphere.nocm.json
templates/vro/common/vmware.vsphere.nocm.json

I've updated the templates to use user vars instead of env vars
This works along and needs to be merged with:
https://github.com/puppetlabs/platform-ci-utils/pull/58

(IMAGES-962) Updated templates not to use ENV vars

---

templates/win/common/vmware.vcenter.cygwin.json

This is breaking the main packer windows build.
Add the missing `

(MAINT) Fix to un-terminated string

---

templates/win/2008/x86_64/vmware.vcenter.cygwin.json
templates/win/common/puppet/hiera.yaml
templates/win/common/puppet/windows_template/data/common.json
templates/win/common/puppet/windows_template/data/common.yaml
templates/win/common/puppet/windows_template/manifests/registry/machine.pp
templates/win/common/scripts/acceptance/bootstrap-packerbuild/OSVersions.Tests.ps1
templates/win/common/scripts/bootstrap/bootstrap-packerbuild.ps1
templates/win/common/scripts/bootstrap/packer-windows-update.ps1
templates/win/common/scripts/common/windows-env.ps1
templates/win/common/scripts/platform9/platform9-post-clone-configuration.ps1
templates/win/common/scripts/provisioners/config-platform9.ps1
templates/win/common/scripts/provisioners/initiate-puppet-configure.ps1
templates/win/common/scripts/provisioners/initiate-windows-update.ps1
templates/win/common/scripts/provisioners/install-cygwin.ps1
templates/win/common/scripts/provisioners/vagrant-arm-host.ps1
templates/win/common/scripts/vmpooler/vmpooler-post-clone-configuration.ps1
templates/win/common/virtualbox.base.json
templates/win/common/virtualbox.base.vagrant.cygwin.json
templates/win/common/virtualbox.slipstream.json
templates/win/common/virtualbox.vagrant.cygwin.json
templates/win/common/vmware.slipstream.json
templates/win/common/vmware.vcenter.bios.base.json
templates/win/common/vmware.vcenter.cygwin.json
templates/win/common/vmware.vcenter.platform9.json
tests/test-syntax.sh

Continue the work from IMAGES-1018 to remove environment variables to
inject data into the build:
1. Switch to .json format as this is easier to consume in powershell. This is done with PS2 support for the Windows-2008/2008r2 platform.
2. This requires changes to the puppet lookup and the variables used to access the .json data.
3. Windows Version/Edition information is passed in via .json file to be consumed by the packer testing.
4. This required moving the platform-package file processing to the bootstrap stage mainly for Windows-2008/2008r2 since .Net 3.5 is required to parse the .json format.
Note - this change has quite a bit of copy/pasta as the packer provider to write the .json file is repeated in several packer scripts. It is hoped to compress most of the windows build into a …

(IMAGES-976) Improve build parameter injection

---

templates/win/10-1511/x86_64/files/platform-packages.ps1
templates/win/10-1607/x86_64/files/platform-packages.ps1
templates/win/2016-core/x86_64/files/platform-packages.ps1
templates/win/2016-fr/x86_64/files/platform-packages.ps1
templates/win/2016/x86_64/files/platform-packages.ps1
templates/win/common/scripts/bootstrap/bootstrap-packerbuild.ps1
templates/win/common/scripts/bootstrap/packer-windows-update.ps1
templates/win/common/scripts/provisioners/initiate-windows-update.ps1

1. Update to Version 2.1.1.2 of the PsWindows Update tool as this appears to run faster for the Windows 10 series of builds. Retain earlier version for win-2012r2 due to WUHistory problem.
2. Add in specific patches to address Windows Service Stack (Update) issues that cause problems for the Windows 2016 build. This hopefully shortens the update time for Windows 2016 by avoding two cumulative update downloads and random failures to do the windows update.
3. Windows 10/2016 now appears to work correctly (and faster) with WSUS so enable these. Windows 10 2016 LTSB still fails to download from WSUS and Win-2012 doesn't get any updates from WSUS, so continue to exclude these.

(IMAGES-1082) update to PSWindowsUpdate 2.1.1.2

---

templates/win/common/vars.json

Drop the _PROD suffix as well as the imaging pipeline now puts the "dev_image" suffix on Dev/Test builds.
The initial run failed with pipeline issues and the version number had 00 for the day number.
So updating version to tomorrow's (build) date.

(IMAGES-1070) April Patch Tuesday Version

---

templates/win/common/scripts/platform9/platform9-post-clone-configuration.ps1
templates/win/common/vars.json

Netbios/lmhosts was disabled pre-sysprep but not re-enabled which causes
issues setting up AD etc.
So set services back to default enabled.

(IMAGES-1100) Enable Netbios/lmhosts

---

templates/win/2012r2-core/x86_64/vars.json

The Pester tests were relaxed for Windows 2012r2 Core due to the lack
of updates (i.e. the slipstream was too successful). This can now be
relaxed with the May 19 update.

(MAINT) Re-Assert Test checks for win-2012r2-core

---

manifests/modules/packer/manifests/networking/params.pp
manifests/modules/packer/manifests/vmtools.pp
manifests/modules/packer/manifests/vsphere.pp
manifests/modules/packer/manifests/vsphere/params.pp
manifests/modules/packer/templates/vsphere/redhat.rb.erb
templates/fedora/30/files/ks.cfg
templates/fedora/30/x86_64/vars.json
templates/fedora/README.md

Added Fedora 30 to puppetlabs-packer:
- installed `libxcrypt-compat` for libcrypt.so.1 required by Puppet-provided ruby
- disabled consistent network device renaming (keep eth0)

(IMAGES-1114) Add packer support for Fedora 30

---

templates/win/10-1809/x86_64/files/platform-packages.ps1
templates/win/10-1809/x86_64/vars.json
templates/win/10-ent/i386/vars.json
templates/win/10-ent/x86_64/vars.json
templates/win/10-next/i386/files/platform-packages.ps1
templates/win/10-next/i386/vars.json
templates/win/10-next/x86_64/files/platform-packages.ps1
templates/win/10-next/x86_64/vars.json
templates/win/10-pro/x86_64/vars.json
templates/win/2019-fr/x86_64/files/platform-packages.ps1
templates/win/2019-fr/x86_64/vars.json
templates/win/2019-ja/x86_64/files/platform-packages.ps1
templates/win/2019-ja/x86_64/files/slipstream-filter
templates/win/2019-ja/x86_64/vars.json

Adding Windows 10 Next to allow testing for the "Next" build of Windows 10 on a continuous basis - this initially will be for Build 1903. This allows the build to be evaluated without breaking the existing pipelines It will also be used to test the preview builds once they are available and 1903 (etc) has been "mainlined" into the Windows 10 build.
Also adding:
1. Windows 10 LTSC (Build 1809)
2. Windows 2019 French and Japanese

(IMAGES-1117) Add Win 10 1903 and 2019 LTSC

---

templates/win/common/vars.json

Its Patch Tuesday time again so update the version.
This rollout also includes new Windows 10 and French/Japanese builds
for Windows 2019.

(IMAGES-1124) Update Version for June 2019 Deploy

---

templates/solaris/11.4/common/files/profile.xml
templates/solaris/11.4/x86_64/vars.json

on Solaris 11.4, name-service/cache uses old nscd application that doesn't know how to handle DNAME record

(maint) disable name-service/cache on Solaris 11.4

---

manifests/modules/packer/manifests/networking/params.pp
templates/centos/7.6/common/files/ks.cfg
templates/centos/7.6/x86_64/vars.json

This adds 7.6 as a template for CentOS. It should look similar to commit a393a8d92ba1a7839d90f4ece2c79a5ccfa1d26c.
I was successfully able to build a box with `PACKER_VM_OUTPUT_DIR=. packer build -var-file=../../common/vars.json -var-file=vars.json ../../../common/virtualbox.base.json`.
I found in the output has the hiera.yaml version 3 is deprecated warning, but that file is not managed in this repository.

Adds CentOS 7.6 template

---

manifests/modules/packer/templates/vsphere/redhat.rb.erb
templates/redhat/7.2-fips/x86_64/vars.json

If the interface cfg file contains "File Managed by Puppet", it will be configured as before, otherwise Network Manager default configuration will be enabled for it

(IMAGES-1145) enable ipv6 on redhat 7 fips

---

templates/centos/7.2-tmpfs/common/files/ks.cfg
templates/centos/7.2-tmpfs/x86_64/vars.json

This is my first time working in this repo.  I want to add a template to CI where tmpfs is enabled in centos 7.2.  This may become the default config, but we want to test this first, so here it is.  I've tested this manually by cloning a vm and running a command, now I want to get it into vmpooler.  The goal here is to reduce the I/O load in CI.  
Not sure if I should do this as 7.2-tmpfs or x86_64-tmpfs but I put it this way because the ks.cfg is in the common folder, and it's the ks.cfg config I need to fix.  
I looked at this documentation:
https://confluence.puppetlabs.com/display/SRE/Linux+Image+Packer+Generation
But did I miss anything further that would suggest how to test this?  I tried reverse engineering the Jenkins job but that was no fun.

(MAINT) Adding a 7.2 image with tmpfs support

---

templates/redhat/7.2-fips/common/files/ks.cfg
templates/redhat/7.2-fips/x86_64/vars.json
templates/redhat/common/files/enable-fips.sh

Our test pipelines for FIPS builds are rapidly exhausting the available pool of entropy.
this adds two tools to fips images help increase the available entropy pool - rng-tools and haveged
This is "fake" entropy and should not be relied on for production, but should be fine for our testing purposes

Add entropy generating tools to fips image

---

manifests/modules/packer/manifests/networking/params.pp
manifests/modules/packer/manifests/vmtools.pp
manifests/modules/packer/manifests/vsphere.pp
manifests/modules/packer/manifests/vsphere/params.pp
manifests/modules/packer/templates/vsphere/redhat.rb.erb
templates/fedora/31/files/ks.cfg
templates/fedora/31/x86_64/vars.json
templates/fedora/README.md

Changed default sshd setting (PermitRootLogin to yes) due to Fedora
changes done in version 31. This allows us to login as root with a
password.
Disabled dnf zchunk compression because of repo metadata retrieval errors.

(IMAGES-1153) Add Fedora 31 template

---

templates/centos/6.9/x86_64/vars.json
templates/centos/7.6/x86_64/vars.json
templates/centos/8.0/x86_64/vars.json
templates/redhat/6.8/x86_64/vars.json
templates/redhat/7.2-fips/x86_64/vars.json
templates/redhat/7.2/x86_64/vars.json
templates/redhat/8.0/x86_64/vars.json
templates/sles/12.1/x86_64/vars.json
templates/sles/15/x86_64/vars.json
templates/ubuntu/16.04/x86_64/vars.json
templates/ubuntu/18.04/x86_64/vars.json

This commit updates the packer templates for all the master platforms
updated as part of QENG-7571 to match the size of the *-8gb templates
created in that ticket.

(QENG-7571) Update master platforms to 8GB RAM

---

templates/win/10-1511/x86_64/files/platform-packages.ps1
templates/win/10-ent/i386/files/platform-packages.ps1
templates/win/10-ent/x86_64/files/platform-packages.ps1
templates/win/10-pro/x86_64/files/platform-packages.ps1
templates/win/2019-core/x86_64/files/platform-packages.ps1
templates/win/2019/x86_64/files/platform-packages.ps1
templates/win/common/puppet/forge-modules.txt
templates/win/common/puppet/windows_group_policy/manifests/init.pp
templates/win/common/scripts/bootstrap/bootstrap-packerbuild.ps1
templates/win/common/scripts/provisioners/initiate-puppet-configure.ps1

A set of fixes that were needed to deliver the January 2020 Patch Tuesday Windows Refresh:
1. Fix Puppet Agent link to use Puppet 6
2. Disable WSUS for Windows 10/2016/2019
3. Add Servicing Stack Updates (SSU) for certain builds to allow update process to run

(IMAGES-1174) January 2020 Windows Patch Tuesday Fixes

---

templates/win/2012/x86_64/x86_64.vmware.slipstream.json
templates/win/7/x86_64/x86_64.vmware.slipstream.json
templates/win/common/google.appveyor.json
templates/win/common/virtualbox.slipstream.json
tests/test-setup.sh

This commit upgrades the version of packer installed by the `Makefile`
to 1.5.1. After doing that upgrade, I found that several templates now
failed the tests because `_comment` fields were provided as arrays,
which is apparently unsupported now. I fixed up the arrays to be regular
strings and all of the templates appear to pass the tests now.

(maint) Upgrade Packer to 1.5.1, fix template errors

---

templates/common/vmware.vcenter.json
templates/win/2008/x86_64/vmware.vcenter.cygwin.json
templates/win/2008/x86_64/vmware.vcenter.slipstream.json
templates/win/common/vmware.vcenter.bios.base.json
templates/win/common/vmware.vcenter.cygwin.json
templates/win/common/vmware.vcenter.platform9.json
templates/win/common/vmware.vcenter.slipstream.json

Packer has not integrated the jetbrains vsphere-* plugins into its core
so switch over all vsphere builds to use this in favour of our local
versioned plugin.
This means the plugins can be removed from the builders.
One less thing to maintain - Yayyyyy

(MAINT) Use Packer vsphere-iso/clone plugins

---

scripts/noop.sh
templates/common/vmware.vcenter.json

This commit adds custom_provisioning_script and
custom_provisioning_env variables to the vmware.vcenter template. This
was done in order to allow running arbitrary scripts after the Puppet
AIO is cleaned up. Examples include: pre-installing PE or pre-loading
PuppetDB.

(DIO-409) Add custom provisioning script

---

scripts/pdbpreload.sh
templates/centos/8.0-pdbpreload/common/files/ks.cfg
templates/centos/8.0-pdbpreload/x86_64/vars.json
templates/centos/8.0/common/files/ks.cfg
templates/centos/8.0/x86_64/vars.json
templates/common/vmware.vcenter.json

Because project_root seems not to be available within vars.json of a template, this sets the custom_provisioning_script to add the project_root to the beginning in the top level vmware.vcenter.json, so the user just has to specify 'scripts/myscript.sh' for custom_provisioning_script.
This adds a new centos 8 template that includes setting up PE with the latest master build, and importing the SLV soak database. This will be used for HA testing.
Because autopart only allocates 50GB max to / and gives the rest to /home, and we need more than this for pdbpreload nodes (and the base centos 8 image so replicas can be provisioned), this changes to manually setting up the root, swap and boot partitions.

(PE-28666) Add centos-8-pdbpreload-x86_64

---

scripts/mono-preload.sh
templates/centos/7.2-mono-2018.1.15-preload/common/files/ks.cfg
templates/centos/7.2-mono-2018.1.15-preload/x86_64/vars.json

This PR creates new packer template data for the creation of a preinstalled centos 7/2018.1.15 mono node to be used in CI.
replaces #488

(PE-29139) Add packer template work for Centos7/ Irving mono preinstall

---

templates/win/10-ent/i386/vars.json
templates/win/10-ent/x86_64/vars.json
templates/win/10-next/i386/vars.json
templates/win/10-next/x86_64/vars.json
templates/win/10-pro/x86_64/vars.json
templates/win/common/puppet/windows_template/manifests/apps/chrome.pp
templates/win/common/puppet/windows_template/manifests/apps/gitforwin.pp
templates/win/common/puppet/windows_template/manifests/apps/notepadplusplus.pp
templates/win/common/puppet/windows_template/manifests/apps/powershell7.pp
templates/win/common/scripts/acceptance/puppet/winpackages.Tests.ps1
templates/win/common/scripts/acceptance/windows-update/WindowsUpdate.Tests.ps1
templates/win/common/scripts/common/puppet-configure.ps1
templates/win/common/scripts/common/test-packerbuild.ps1
templates/win/common/scripts/common/windows-env.ps1
templates/win/common/scripts/provisioners/cleanup-host.ps1
templates/win/common/vars.json
templates/win/common/vmpooler_deploy_record.sh
templates/win/common/vmware.vcenter.bios.base.json
templates/win/common/vmware.vcenter.cygwin.json
templates/win/common/vmware.vcenter.slipstream.json
util/VMWarePowerCLI/FixupNov2020Images.ps1

Generate the Windows November 2020 Patch Tuesday Image Refresh.
This picks up serious CVE-2020-3941 as well as updates to:
1. Powershell 7.1.0
2. NotePad++ 7.9.1
3. Google chrome 86.0.4240.198
4. Git for Windows 2.29.2.2
5. vmware tools 11.2.0 (via boot process)
Windows 10 is also updated to:
1. win-10-ent: Build 2004
2. win-10-next: Build 2009 (20H2)
Fixed issue with pswindows update testing - seems to be a bug in This
since Build 2004 where the get-wuhistory hangs - adding last 2 to the
command appears to be a vaid workaround.
Google appears to install in the Program Files directory (and no longer
in the x86 one) so adjust in scripting.
Filter our Packer Environment Files on the Forcefully delete so as to
avoid throwing (albeit non-fatal) errors in the cleanup scripts at the
end.
Create …

(IMAGES-1231) November 2020 Windows Image Refresh

---

templates/win/2019-mock/x86_64/vars.json
templates/win/common/vars.json

This is mainly to ensure we don't hammer the existing vmpooler images.
Also fix the win 2019 mock testing parameter.

(IMAGES-1242) Update version for testing

---

manifests/base.pp
manifests/modules/packer/manifests/networking/params.pp
manifests/modules/packer/manifests/vsphere.pp
manifests/modules/packer/manifests/vsphere/repos.pp
manifests/modules/packer/manifests/vsphere/updates.pp
scripts/kurl.sh
templates/centos/8.0-pdbpreload/x86_64/vars.json
templates/centos/8.0/x86_64/vars.json
templates/centos/8.3-kurl-beta/common/files/ks.cfg
templates/centos/8.3-kurl-beta/x86_64/vars.json
templates/centos/README.md

Adds a CentOS 8 image with https://kurl.sh pre-installed based on CD4PE's Beta channel.

(REPLATS-8) Add kURL image for testing

---

manifests/modules/packer/manifests/puppet.pp

As part of updating the new release signing key, I found some code
here that also referenced the long-removed PC1 repo.
Deleted it.

(RE-13438) Remove old GPG key & obsolete PC1 references

---

scripts/kurl.sh
scripts/local-git-checkout.sh
templates/centos/8.3-kurl-beta/x86_64/vars.json
templates/common/vmware.vcenter.json

When a kurl vm is checked out, there's a multi step process to get
containerd and the k8s services running again. It becomes more
complicated when the host ip has changed and k8s services need to be
reconfigured for the new ip.
In order to make it simple for anyone manually checking out a kurl vm to
reset it to a working state, this patch pulls down the restart-k8s.sh
script from the kurl_test repo into /root so it's available to be run
when a vm is checked out.
There doesn't seem to be a straight forward mechanism for including
arbitrary files with puppetlabs-packer without modifying the
templates/common/vmware.vcenter.json to include an additional file
provisioner. But that would affect all the images using that template.

(REPLATS-168) Add a k8s restart script for kurl image

---

manifests/modules/packer/templates/vsphere/redhat.rb.erb
templates/fedora/34/files/ks.cfg
templates/fedora/34/x86_64/vars.json

Disabled systemd-resolved and restored /etc/resolv.conf as
normal file.

(IMAGES-1259) Fedora 34 fixes

---

templates/centos/8.3-kurl-beta/x86_64/vars.json

...to bring in Weave 2.8.1. We've been seeing transient issues with
weave networkpolicy rules not being up to date after a restarted vm and
want to see if pulling in the newer puppet-application-manager builds
that include a newer weave-net improve the problem.

(REPLATS-169) Bump centos-8.3-kurl image version to 0.1.1

---

templates/centos/8.3-kurl-beta/x86_64/vars.json

This will pull in the latest restart_k8s.sh script from the kurl_test
repo, which was updatedly more recently than the image.

(REPLATS-360) Bump centos-8.3-kurl image version to 0.1.2

---

templates/centos/8.3-kurl-beta/x86_64/vars.json

The 0.1.2 never got to the pooler, but we have
puppet-application-manager changes to pull in since then anyway, so
revving a new version.

(REPLATS-360) Bump centos-8.3-kurl image version to 0.1.3

---

templates/centos/8.3-kurl-beta/x86_64/vars.json

...and switch channel from standalone to standalone-beta. There are
changes from the past month that we want to test before the next
release.

(REPLATS-360) Bump centos-8.3-kurl image version to 0.1.4

---

scripts/kurl.sh
templates/centos/8.3-kurl-beta/x86_64/vars.json

Stops Kubelet before shutdown. The packer build fills the disk with 0s to compress the image, which otherwise causes Kubelet to start erasing unused images that we still need.

(maint) Fix missing images for airgap tests

---

templates/centos/8.3-kurl-beta/x86_64/vars.json

Pulls in newer kurl_test restart_k8s.sh script.

(REPLATS-360) Bump centos-8.3-kurl image version to 0.1.6

---

templates/centos/8.3-kurl-beta/common/files/ks.cfg
templates/centos/8.3-kurl-beta/x86_64/vars.json

The script will install it as well, but may as well have it on the vm,
and we need to bump version anyway to pull the new script in.

(REPLATS-360) Add ipvsadm used by restart_k8s.sh

---

scripts/kurl.sh
templates/centos/8.3-kurl-beta/common/files/ks.cfg
templates/centos/8.3-kurl-beta/x86_64/vars.json

We're seeing transient issues with pods starting up after reinitializing via kubeadm. Drain all pods before we stop kubelet and create the image to ensure pods have a chance to safely shutdown.
Also prevents kubelet and containerd from starting on startup as the first thing we do in the restart script is to stop them. This avoids having to cleanup pods again.

(maint) Drain pods before imaging

---

templates/centos/8.3-kurl-beta/x86_64/vars.json

Update image for templating changes in 3318e6a and 7446d02 that no
longer pull in restart script. Forgot to put version bump in that
branch before merge.

(REPLATS-360) Bump centos-8.3-kurl image to 0.2.0

---

templates/common/vmware.vcenter.json

A file provisioner in the vmware.vcenter.json template was missing [the required `source` parameter](https://www.packer.io/docs/provisioners/file#configuration-reference-1) and instead had the optional `sources` parameter.
I believe that this was causing an imaging pipeline to fail: https://jenkins-sre.delivery.puppetlabs.net/view/imaging/view/Redhat/job/imaging_redhat-9.0_x86_64_vmware_vcenter_packer_build_packer/2/console

(maint) Corrects template file parameter

---

templates/common/vmware.vcenter.json

When I pulled the file provisioner back in from 3318e6a, I forgot to
include the default value for custom_files_to_upload. Consequently other
images using vmware.vcenter.json as their base template would fail,
since they had no value set here. Readding as /dev/null so that the
builder is effectively a noop unless an image specifies something to
copy.
---
@mhashizume this also reverts 5b90b4 because when I'm using custom_files_to_upload, I'm passing an array, so I believe sources is the required parameter. If you made that change because you were trying to correct my mistake with the default, then we're probably okay? But if something else was broken, please let me know. Thanks!

(REPLATS-514) Fix custom files to upload default

---

scripts/kurl.sh
templates/redhat/8.4-kurl-beta/x86_64/vars.json

This was working around a bug in the local dnf repositories used by Kurl
when building the redhat-8.4-kurl-beta image.
As of https://kurl.sh/release-notes/v2021.12.01-0, kurl includes this
workaround itself. Consequently, the kurl.sh script was failing because
dnf would exit non-zero when we tried to `dnf module reset kurl.local`
because Kurl's install.sh script had already removed it...

(PT-582) Remove dnf module workaround from kurl.sh script

---

manifests/modules/packer/manifests/vsphere/repos.pp
templates/redhat/9.0/x86_64/vars.json

Currently, the codeready repository is being added by the packer manifest, but then subsequently purged by the vsphere manifest. This assures that the repository is not purged.

(maint) Adds RHEL 9 codeready repo

---

scripts/cleanup-scrub.sh

`awk` in the Mac section of the cleanup script uses the wrong variable to get the major version of the OS. Some examples from macOS 10.15:
```
steeper-paradox:~ root# sw_vers -productVersion | awk -F "." '{print $2}'
15
steeper-paradox:~ root# sw_vers -productVersion | awk -F "." '{print $1}'
10
```
And macOS 12:
```
esthetic-idea:~ root# sw_vers -productVersion | awk -F "." '{print $2}'
2
esthetic-idea:~ root# sw_vers -productVersion | awk -F "." '{print $1}'
12
```

(maint) Updates cleanup script for macOS

---

templates/redhat/8.4-kurl-beta/x86_64/vars.json

Brings in puppetlabs/puppet-application-manager@2022-04-05-rc1

(REPLATS-647) Bump kurl-beta vm to version 0.3.15

---

templates/redhat/8.4-kurl-beta/x86_64/vars.json

Brings in puppetlabs/puppet-application-manager@2022-04-08-rc1
This brings in kURL v2022.04.08-0 which has a patch to lower envoy
resource requirements that should fix our problem starting Comply on the
resource constrained test image.

(REPLATS-647) Bump kurl-beta vm to version 0.3.16

---

scripts/kurl.sh
templates/redhat/8.4-kurl-beta/x86_64/vars.json

Brings in puppetlabs/puppet-application-manager@2022-05-25-rc1
This brings in kURL v2022-05-19-0 and kots 1.70.1. This includes patches
to containers addressing some of the CVEs listed in REPLATS-690.

(REPLATS-702) Bump kurl-beta vm to version 0.3.17
