templates/centos-5.11/x86_64.virtualbox.base.json, templates/centos-6.6/files/x86_64.ks, templates/centos-6.6/i386.vmware.base.json, templates/centos-6.6/x86_64.vmware.base.json, templates/debian-6.0.10/x86_64.virtualbox.base.json, templates/ubuntu-12.04/files/preseed.cfg, templates/ubuntu-14.04/x86_64.virtualbox.base.json
While building new boxes for release on Vagrant Cloud I found a few
items missed in #28.  This commit addresses thoses issues.
=> (maint) Fixups for Vagrant Box Updates

bin/vagrantclouder
This PR adds the script that's used to ship and release boxes on VagrantCloud.  This has been managed as a one-off script on the imaging boxes.  Adding three commits to document the lifecycle of the script.
=> vagrantcloud automation

scripts/cleanup-puppet.sh, templates/centos-7.0/x86_64.ec2.nocm.json, templates/debian-7.8/x86_64.ec2.nocm.json
These commits update the necessary portions of the packer configs required to produce AMI artifacts for Debian 7.8 and CentOS 7.
=> (RE-5967) update ec2 configs

templates/debian-8.2/CHANGELOG, templates/debian-8.2/files/preseed.cfg, templates/debian-8.2/i386.virtualbox.base.json, templates/debian-8.2/i386.virtualbox.vagrant.nocm.json, templates/debian-8.2/i386.virtualbox.vagrant.puppet.json, templates/debian-8.2/i386.vmware.base.json, templates/debian-8.2/i386.vmware.vagrant.nocm.json, templates/debian-8.2/i386.vmware.vagrant.puppet.json, templates/debian-8.2/x86_64.virtualbox.base.json, templates/debian-8.2/x86_64.virtualbox.vagrant.nocm.json, templates/debian-8.2/x86_64.virtualbox.vagrant.puppet.json, templates/debian-8.2/x86_64.vmware.base.json, templates/debian-8.2/x86_64.vmware.vagrant.nocm.json, templates/debian-8.2/x86_64.vmware.vagrant.puppet.json
This commit adds Debian 8.2/jessie nocm and puppet-agent
packer configs for both VMware and VirtualBox.
=> (RE-6109) Add packer configs for Debian 8

templates/debian-8.2/i386.vsphere.nocm.json, templates/debian-8.2/x86_64.vsphere.nocm.json
This commit adds vsphere-nocm packer templates.  The vSphere
artifact is meant to be used with the vmpooler.
=> (RE-6139) add Debian 8 vsphere/vmpooler configs

manifests/modules/packer/templates/vsphere/debian.rb.erb, templates/debian-6.0.10/i386.vsphere.nocm.json, templates/debian-6.0.10/x86_64.vsphere.nocm.json, templates/debian-8.0/CHANGELOG, templates/debian-8.0/files/preseed.cfg, templates/debian-8.0/i386.vmware.base.json, templates/debian-8.0/i386.vsphere.nocm.json, templates/debian-8.0/x86_64.vmware.base.json, templates/debian-8.0/x86_64.vsphere.nocm.json
This commit adds Debian 8.0 ( no updates ) vsphere-nocm
packer templates.  The vSphere artifact is meant to be
used with the vmpooler.
=> (maint) add Debian 8.0 vsphere/vmpooler configs and update bootsrtrap erb

scripts/bootstrap-puppet.sh, scripts/cleanup-ec2.sh, scripts/cleanup-puppet.sh, templates/centos-7.0/x86_64.ec2.nocm.json, templates/debian-7.8/x86_64.ec2.nocm.json, templates/ubuntu-14.04/x86_64.ec2.nocm.json, templates/ubuntu-15.10/x86_64.ec2.nocm.json
This PR adds a packer template to create an AMI artifact for Ubuntu 15.10 amd64.  It also slightly changes the way we bootstrap and cleanup puppet on ec2 builds.
=> (RE-6481) Create packer template for Ubuntu 15.10 amd64 AMI

manifests/modules/packer/manifests/vsphere/networking.pp, manifests/modules/packer/templates/vsphere/ubuntu.rb.erb, templates/ubuntu-16.04/files/preseed.cfg, templates/ubuntu-16.04/i386.vmware.base.json, templates/ubuntu-16.04/i386.vsphere.nocm.json, templates/ubuntu-16.04/x86_64.ec2.nocm.json, templates/ubuntu-16.04/x86_64.vmware.base.json, templates/ubuntu-16.04/x86_64.vsphere.nocm.json
Standard beta for Ubuntu does not come out until Beta 2.  This attempts to build with a live nightly
**Note** Only x86_64 built and tested.
=> (RE-6593) Ubuntu 16.04 Beta

templates/centos-5.11/vagrantcloud.yaml, templates/centos-6.6/vagrantcloud.yaml, templates/centos-7.2/vagrantcloud.yaml, templates/debian-7.8/vagrantcloud.yaml, templates/debian-8.2/vagrantcloud.yaml, templates/ubuntu-12.04/vagrantcloud.yaml, templates/ubuntu-14.04/vagrantcloud.yaml
This commit updates the description for the AIO puppet boxes to show their relation to the Puppet Enterprise version.
=> (maint) update box descriptions

manifests/modules/packer/manifests/networking/params.pp, manifests/modules/packer/manifests/vsphere/networking.pp, manifests/modules/packer/manifests/vsphere/params.pp, manifests/modules/packer/templates/vsphere/redhat.rb.erb, templates/scientific-7.2/files/x86_64.ks, templates/scientific-7.2/x86_64.vmware.base.json, templates/scientific-7.2/x86_64.vmware.vagrant.nocm.json, templates/scientific-7.2/x86_64.vsphere.nocm.json
This commit adds a Scientific 7.2 vsphere-nocm packer template.  The
vSphere artifact is meant to be used with the vmpooler.
=> (RE-6745) add Scientific 7.2 vsphere/vmpooler config

templates/debian-6.0.10/files/preseed.cfg, templates/debian-7.8/files/preseed.cfg, templates/debian-8.0/files/preseed.cfg, templates/debian-8.2/files/preseed.cfg
Spotted and hopefully fixed a typo in the Debian preseed config files
=> Fix typo in Debian preseed partitioning config option

manifests/windows/windows_template/manifests/local_group_policies.pp
=> (RE-7685) Set Powershell Unrestricted Policy

manifests/base.pp, manifests/modules/packer/manifests/networking/params.pp, scripts/cleanup-puppet.sh, scripts/install-puppet-enterprise.sh, templates/fedora-24/i386.libvirt.base.json, templates/fedora-24/i386.libvirt.vagrant.nocm.json, templates/fedora-24/i386.libvirt.vagrant.puppet.json, templates/fedora-24/x86_64.libvirt.base.json, templates/fedora-24/x86_64.libvirt.vagrant.nocm.json, templates/fedora-24/x86_64.libvirt.vagrant.puppet.json
Should I add puppet3 boxes, both PE en OS ?
other distros will be added in their own PR's
=> [CPR-371] Add libvirt vagrant boxes for fedora24

templates/windows-2012r2/x86_64.vmware.base.json
Fix a typo causing pipeline failure.
=> (MAINT) Fix json typo for base

templates/windows-2012r2/x86_64.vmware.base.json
Needed to get the build to work on the Centos machines.
=> (MAINT) Use VMWare Tools var

manifests/windows/windows_template/manifests/local_group_policies.pp, templates/windows-2016rtm/files/win-2016rtm-x86_64-std.pp, templates/windows-2016rtm/x86_64.vmware.vsphere.cygwin.json
1. Add registry key to disable network wizard prompt at login.
2. Also some maint to remove TODO comments that are no longer relevent (as the TODOs is Done)
3. (MAINT) commit to copy Chrome defaults into this build from win-2012
=> (RE-7942) Turn off Network Location Wizard

scripts/windows/windows-env.ps1
Write the name of the key to the console as it is being edited.
Useful for debugging logs
=> (MAINT) Add notification to registry key edit

templates/fedora-23/files/Vagrantfile.libvirt, templates/fedora-23/i386.libvirt.base.json, templates/fedora-23/i386.libvirt.vagrant.nocm.json, templates/fedora-23/i386.libvirt.vagrant.puppet.json, templates/fedora-23/x86_64.libvirt.base.json, templates/fedora-23/x86_64.libvirt.vagrant.nocm.json, templates/fedora-23/x86_64.libvirt.vagrant.puppet.json
Added also a Vagrant template, which will be included in the box.  This solve my issues with the kernel oops during boot.  Solution : https://bugzilla.redhat.com/show_bug.cgi?id=1283989
=> adds fedora 23 vagrant-libvirt templates

README.md, templates/windows-2012/README.md, templates/windows-2012r2/README.md, templates/windows-2016rtm/README.md
These are now available on Confluence - put a reference in here.
=> (IMAGES-47) Reference to Windows/Packer Docs

scripts/windows/clean-disk-dism.ps1, scripts/windows/clean-disk-sdelete.ps1, scripts/windows/cleanup-host.ps1, scripts/windows/init/vmpooler-arm-host.ps1, scripts/windows/install-cygwin.ps1, scripts/windows/install-win-packages.ps1, scripts/windows/windows-env.ps1, templates/windows-2008r2/files/autounattend.xml, templates/windows-2008r2/files/config-vmware-vsphere-cygwin.ps1, templates/windows-2008r2/files/windows-2008r2-x86_64-vmware.package.ps1, templates/windows-2008r2/x86_64.vmware.base.json, templates/windows-2008r2/x86_64.vmware.vsphere.cygwin.json, templates/windows-2012/files/config-vmware-vsphere-cygwin.ps1, templates/windows-2012/files/windows-2012-x86_64-vmware.package.ps1, templates/windows-2012/x86_64.vmware.base.json, templates/windows-2012r2/files/config-vmware-vsphere-cygwin.ps1, templates/windows-2012r2/files/windows-2012r2-x86_64-vmware.package.ps1, templates/windows-2012r2/x86_64.vmware.base.json, templates/windows-2016/files/config-vmware-vsphere-cygwin.ps1, templates/windows-2016/files/windows-2016-x86_64-vmware.package.ps1, templates/windows-2016/x86_64.vmware.base.json
Use the KB2852386 hotfix for cleanmgr to clean the windows udpate
(winsxs) area.
Also use cleanmgr across all OS's for a more comprehensive disk tidy up.
MAINT commit to be added to update other OS package files to install
desktop-experience
NB - this is layered on top of #140 - so needs rebased once that PR is merged.
Putting this up now as WIP for @glennsarti to review - not fully tested yet.
=> (IMAGES-101) Add Win-2008R2 Win Update Cleanup

templates/windows-10/README.md, templates/windows-10/files/autounattend.xml, templates/windows-10/files/config-vmware-vsphere-cygwin.ps1, templates/windows-10/files/generalize-packer.autounattend.xml, templates/windows-10/files/post-clone.autounattend.xml, templates/windows-10/files/win-10-x86_64-std.pp, templates/windows-10/files/windows-10-x86_64-vmware.package.ps1, templates/windows-10/x86_64.vmware.base.json, templates/windows-10/x86_64.vmware.vsphere.cygwin.json
Add the Windows 10 Packer Templates.
=> (IMAGES-22) Windows 10 Template

manifests/modules/packer/manifests/vsphere/networking.pp, manifests/modules/packer/templates/vsphere/ubuntu.rb.erb, templates/ubuntu-16.10/CHANGELOG, templates/ubuntu-16.10/files/preseed.cfg, templates/ubuntu-16.10/i386.virtualbox.base.json, templates/ubuntu-16.10/i386.virtualbox.vagrant.nocm.json, templates/ubuntu-16.10/i386.virtualbox.vagrant.puppet.json, templates/ubuntu-16.10/i386.vmware.base.json, templates/ubuntu-16.10/i386.vmware.vagrant.nocm.json, templates/ubuntu-16.10/i386.vmware.vagrant.puppet.json, templates/ubuntu-16.10/i386.vsphere.nocm.json, templates/ubuntu-16.10/vagrantcloud.yaml, templates/ubuntu-16.10/x86_64.ec2.nocm.json, templates/ubuntu-16.10/x86_64.virtualbox.base.json, templates/ubuntu-16.10/x86_64.virtualbox.vagrant.nocm.json, templates/ubuntu-16.10/x86_64.virtualbox.vagrant.puppet.json, templates/ubuntu-16.10/x86_64.vmware.base.json, templates/ubuntu-16.10/x86_64.vmware.vagrant.nocm.json, templates/ubuntu-16.10/x86_64.vmware.vagrant.puppet.json, templates/ubuntu-16.10/x86_64.vsphere.nocm.json
=> (IMAGES-384) Add Yakkety to puppetlabs-packer

.gitignore, .travis.yml, Makefile, README.md, templates/centos-7.0/x86_64.ec2.nocm.json, templates/debian-7.8/x86_64.ec2.nocm.json, templates/ubuntu-14.04/x86_64.ec2.nocm.json, tests/test-setup.sh, tests/test-syntax.sh
and plug them in through tavis
=> Add tests to validate packer syntax

manifests/modules/packer/manifests/vmtools.pp, manifests/modules/packer/manifests/vsphere/networking.pp, templates/debian-9.0/CHANGELOG, templates/debian-9.0/files/preseed.cfg, templates/debian-9.0/i386.vmware.base.json, templates/debian-9.0/i386.vsphere.nocm.json, templates/debian-9.0/x86_64.vmware.base.json, templates/debian-9.0/x86_64.vsphere.nocm.json
This is based on the Debian 9 alpha 8 installer release from 2016-11-12.
=> (IMAGES-345) Debian 9.0 alpha templates

manifests/modules/packer/manifests/networking/params.pp, manifests/modules/packer/manifests/updates.pp, manifests/modules/packer/manifests/vmtools/params.pp, manifests/modules/packer/manifests/vsphere/params.pp, manifests/modules/packer/manifests/vsphere/repos.pp, manifests/modules/packer/templates/vsphere/sles.rb.erb, scripts/bootstrap-aio.sh, templates/sles-12.1/CHANGELOG, templates/sles-12.1/files/sles-12-sp1-x86_64-autoinst.xml, templates/sles-12.1/x86_64.vmware.base.json, templates/sles-12.1/x86_64.vmware.vsphere.nocm.json, templates/sles-12.2/CHANGELOG, templates/sles-12.2/files/sles-12-sp2-x86_64-autoinst.xml, templates/sles-12.2/x86_64.vmware.base.json, templates/sles-12.2/x86_64.vmware.vsphere.nocm.json
This adds SLES sp1 and sp2 support
=> sles-12 sp1 and sp2

manifests/modules/packer/manifests/vmtools.pp, manifests/modules/packer/manifests/vsphere/networking.pp, templates/ubuntu-16.04/i386.vmware.base.json, templates/ubuntu-16.04/i386.vmware.vsphere.nocm.json, templates/ubuntu-16.04/x86_64.vmware.base.json, templates/ubuntu-16.04/x86_64.vmware.vsphere.nocm.json
Explicitly set the local to en_US.UTF-8 in the initial machine
configuration.
This PR also has MAINT refactor to use the AIO puppet configuration method.
=> (IMAGES-498) Set EN_US local to UTF-8

.gitignore, acceptance/Gemfile, acceptance/hosts.yaml.erb, acceptance/test.rb
Setup an acceptance test structure for Packer Builds.
This is tied to jenkins JJB definitions associated with this ticket.
=> (IMAGES-490) Packer Acceptance Test Environment

templates/debian-9.0/files/preseed.cfg, templates/debian-9.0/i386.vmware.base.json, templates/debian-9.0/i386.vmware.vsphere.nocm.json, templates/debian-9.0/x86_64.vmware.base.json, templates/debian-9.0/x86_64.vmware.vsphere.nocm.json
RC3 has just been released, so update the Debian 9.0 iso to use this.
=> (IMAGES-532) Update Debian ISO to RC3

manifests/modules/packer/manifests/vmtools.pp, manifests/modules/packer/manifests/vmtools/params.pp, manifests/modules/packer/manifests/vsphere/params.pp, manifests/modules/packer/manifests/vsphere/repos.pp, manifests/modules/packer/templates/vsphere/redhat.rb.erb, templates/oracle-6.7/CHANGELOG, templates/oracle-6.7/files/i386.ks, templates/oracle-6.7/files/x86_64.ks, templates/oracle-6.7/i386.vmware.base.json, templates/oracle-6.7/i386.vmware.vsphere.nocm.json, templates/oracle-6.7/x86_64.vmware.base.json, templates/oracle-6.7/x86_64.vmware.vsphere.nocm.json
base and vsphere/pooler images
=> Add oracle 6.7

manifests/modules/packer/manifests/networking/params.pp, manifests/modules/packer/manifests/vmtools.pp, manifests/modules/packer/manifests/vsphere.pp, templates/fedora-26/files/ks.cfg, templates/fedora-26/x86_64.vmware.base.json, templates/fedora-26/x86_64.vmware.vsphere.nocm.json
This is blocked on getting the fedora-26 repo up on http://osmirror.delivery.puppetlabs.net/.
Ticket: https://tickets.puppetlabs.com/browse/IMAGES-593
=> (IMAGES-592) Add Fedora 26

templates/win-7-wmf5/README.md, templates/win-7-wmf5/files/slipstream-filter, templates/win-7-wmf5/files/x86_64/platform-packages.ps1, templates/win-7-wmf5/x86_64.vars.json
Add WMF5 (Powershell 5) Windows 7 builds to the platform suite.
=> (IMAGES-612) Add Win-7 WMF5 builds.

templates/linux/common/vmware.base.json
We'd like var files to be able to override and specify multiple
provisioning scripts.
=> (maint) Convert the provisioning scripts into an overridable var

manifests/modules/packer/manifests/networking/params.pp, templates/linux/redhat/7.0-fips/common/files/ks.cfg, templates/linux/redhat/7.0-fips/x86_64/vars.json, templates/linux/redhat/README.md, templates/linux/redhat/common/files/enable-fips.sh, templates/linux/redhat/common/files/enable-rhel-repos.sh, templates/linux/redhat/common/vars.json
This is a refactoring of @jsane's PR-223 to make it follow our recent repo restructuring, and includes some minor cleanups and improvements as well.
=> (IMAGES-656) Add a template for a FIPS-mode enabled Redhat 7 image

scripts/windows/start-pswindowsupdate.ps1, templates/win-10-1607/x86_64.vars.json, templates/win-10-ent/i386.vars.json, templates/win-10-ent/x86_64.vars.json, templates/win-10-pro/x86_64.vars.json, templates/win-2008/x86_64.vars.json, templates/win-2008r2-wmf5/x86_64.vars.json, templates/win-2008r2/x86_64.vars.json, templates/win-2012/x86_64.vars.json, templates/win-2012r2-core/x86_64.vars.json, templates/win-2012r2-fr/x86_64.vars.json, templates/win-2012r2-ja/x86_64.vars.json, templates/win-2012r2-wmf5/x86_64.vars.json, templates/win-2012r2/x86_64.vars.json, templates/win-2016-core/x86_64.vars.json, templates/win-2016/x86_64.vars.json, templates/win-7-wmf5/x86_64.vars.json, templates/win-7/x86_64.vars.json, templates/win-81/x86_64.vars.json
1. Set the Version number manually as (as autogenerated versions not there yet)
2. Force-Enable the Patch Tuesday patches for early checking
=>  (IMAGES-708) January 2018 Patch Tuesday Update

manifests/modules/packer/manifests/networking/params.pp, manifests/modules/packer/manifests/vmtools.pp, manifests/modules/packer/manifests/vsphere.pp, manifests/modules/packer/manifests/vsphere/repos.pp, templates/fedora/27/x86_64/vars.json
I'm able to build the vmware base template with this PR.
=> (IMAGES-726) Add template for Fedora 27 x86_64

manifests/modules/packer/manifests/vsphere/repos.pp, templates/redhat/7.2/common/files/ks.cfg, templates/redhat/7.2/x86_64/vars.json, templates/redhat/common/files/enable-rhel-repos.sh
This adds a packer template for RHEL 7.2, with additional changes to
use our internal RHEL mirror and make the script which enables the
repo to be used across other RHEL versions.
=> (IMAGES-742) RHEL 7.2 template addition and fixes

manifests/modules/packer/manifests/repos.pp, manifests/modules/packer/manifests/vsphere/repos.pp, templates/redhat/7.2/x86_64/vars.json
This updates the RHEL repo urls to new values that should work properly
with yum package groups.
=> (maint) Update RHEL repo urls

tests/test-setup.sh
0.12.0 is really old, so bumped to the latest version.
Also started adding vagrant configs for centos 7.4 for
* vagrant-libvirt
* vagrant-virtualbox
* vagrant docker
both for nocm and puppet configs.
Don't know what the policies will be from your side .... Should I create a PR or just keep it in a separate project ???
=> bump to 1.2.1

templates/win/10-1607/x86_64/vars.json, templates/win/10-ent/i386/vars.json, templates/win/10-ent/x86_64/vars.json, templates/win/10-pro/x86_64/vars.json, templates/win/2008/x86_64/vars.json, templates/win/2008r2-wmf2/x86_64/vars.json, templates/win/2008r2-wmf3/x86_64/vars.json, templates/win/2008r2-wmf5/x86_64/vars.json, templates/win/2008r2/x86_64/vars.json, templates/win/2012/x86_64/vars.json, templates/win/2012r2-core/x86_64/vars.json, templates/win/2012r2-fr/x86_64/vars.json, templates/win/2012r2-ja/x86_64/vars.json, templates/win/2012r2-wmf5/x86_64/vars.json, templates/win/2012r2/x86_64/vars.json, templates/win/2016-core/x86_64/vars.json, templates/win/2016/x86_64/vars.json, templates/win/7-wmf5/x86_64/vars.json, templates/win/7/x86_64/vars.json, templates/win/81/x86_64/vars.json
Set the version to todays date to ensure no clashes with previous
builds.
=> (MAINT) Update Version on all Windows Builds

templates/vro/7.3/x86_64/vars.json, templates/vro/README.md, templates/vro/common/files/vcloud-bootstrap, templates/vro/common/scripts/configure-for-vsphere.sh, templates/vro/common/vmware.vsphere.nocm.json
This is built from an existing OVA, downloaded here: https://my.vmware.com/web/vmware/details?productId=650&downloadGroup=VROVA_730#product_downloads
=> (IMAGES-758) Add vsphere template for VRO 7.3 x86_64

manifests/modules/packer/manifests/vmtools.pp, manifests/modules/packer/manifests/vsphere/networking.pp, manifests/modules/packer/templates/vsphere/ubuntu.rb.erb
Adds 18.04 as a valid release version alongside past versions.
=> (IMAGES-752) Allow for Ubuntu 18.04 in packer modules

templates/win/common/files/AutoUnattendTemplate.xml, templates/win/common/puppet/windows_group_policy/metadata.json, templates/win/common/scripts/google/install-appveyor-packages.ps1, templates/win/common/scripts/provisioners/generate-slipstream.ps1, templates/win/common/scripts/vmpooler/DisableNetworkAdapterPnPCapabilities.ps1, templates/win/common/scripts/vmpooler/vmpooler-post-clone-configuration.ps1
Following the last commit - did a check for remaining white spaces and
pushing up a general MAINT fix to cover the 6 remaining files.
=> (MAINT) Fix remaining whitespace issues

templates/win/common/puppet/windows_template/manifests/registry/machine.pp, templates/win/common/scripts/config/vmpooler-clone-arm-startup.reg, templates/win/common/scripts/vmpooler/vmpooler-clone-startup.ps1, templates/win/common/scripts/vmpooler/vmpooler-post-clone-configuration.ps1
Small fixes to the Windows/Packer builds including:
1. IMAGES-852 - Fix initial BGInfo run error
=> (IMAGES-852) Fix BGinfo Error and other small packer/windows issues

templates/win/common/puppet/windows_template/manifests/policies/local_group_policies.pp, templates/win/common/scripts/bootstrap/start-pswindowsupdate.ps1, templates/win/common/scripts/common/windows-env.ps1, templates/win/common/scripts/provisioners/clean-disk-dism.ps1, templates/win/common/scripts/provisioners/clean-disk-sdelete.ps1, templates/win/common/scripts/provisioners/cleanup-host.ps1, templates/win/common/scripts/vmpooler/vmpooler-clone-startup.ps1, templates/win/common/scripts/vmpooler/vmpooler-post-clone-configuration.ps1, templates/win/common/virtualbox.base.json, templates/win/common/virtualbox.vagrant.cygwin.json
Disabling this for Windows 10 as it delays the first login sequence.
All in the cause of reducing the machine prep time at first boot.
=> (IMAGES-853) Disable First Logon Animation

templates/win/2019/x86_64/vars.json
Preview release has updated (and current one has expired), so update ISO
name and checksum.
=> (WIP) (IMAGES-902) Update Windows Server 2019 Preview

templates/win/common/scripts/common/windows-env.ps1
Adding one more SilentlyContinue to keep the Core Builds Happy.
=> (IMAGES-901) Redux - Ignore the post-restart.bat delete

templates/win/common/gen-xslt.sh
Revert "(IMAGES-907) Set Firmware to BIOS for vcenter/vmware builds"
This reverts commit b363dace727201ac48781f9ab0be360666aaa3f1.
=> (IMAGES-907) Revert BIOS/EFI Hack

templates/win/2008/x86_64/vmware.vcenter.cygwin.json
Add a custom Win-2008 vcenter build script to allow this to be
built on the "new" vcenter infrastructure - this is mostly
copy/pasta taking into account that most of the powershell has to
be run at elevated level.
=> (IMAGES-907) Upate Win-2008 to work with vcenter build

templates/win/common/scripts/bootstrap/packer-windows-update.ps1, templates/win/common/scripts/provisioners/generate-slipstream.ps1, templates/win/common/vars.json
Updating the Windows Image Version Number to reflect the up-coming
Sept-2018 Patch Tuesday Builds.
Also a minor code review update.
=> (IMAGES-918) Update win version for Patch Tuesday Sept 2018

templates/win/2008/x86_64/vmware.vcenter.cygwin.json, templates/win/common/scripts/bootstrap/bootstrap-packerbuild.ps1, templates/win/common/scripts/provisioners/initiate-windows-update.ps1
Trailing fixes needed for the Sept-18 Patch Tuesday refresh
1. French localised Administrator name for the scheduled Task work.
2. Bootstrap scripts for win-2008
=> (IMAGES-918) Minor Deployment Fixes

templates/win/2008/x86_64/vmware.vcenter.cygwin.json, templates/win/common/files/AutoUnattendTemplate.xml, templates/win/common/files/Autounattend.xslt, templates/win/common/files/PostCloneTemplate.xml, templates/win/common/gen-xslt.sh, templates/win/common/scripts/bootstrap/bootstrap-packerbuild.ps1, templates/win/common/scripts/provisioners/initiate-windows-update.ps1, templates/win/common/scripts/provisioners/vagrant-arm-host.ps1, templates/win/common/scripts/vmpooler/vmpooler-post-clone-configuration.ps1, templates/win/common/vars.json, templates/win/common/virtualbox.vagrant.cygwin.json, templates/win/common/vmware.vcenter.cygwin.json
Issue with French/German localised Admin names for the scheduled Task work.
Fix so that we can pass the correct Username/Password into the scripts.
=> (IMAGES-918) Localise Admin User/Password

manifests/modules/packer/manifests/vmtools.pp, manifests/modules/packer/manifests/vsphere.pp, manifests/modules/packer/manifests/vsphere/networking.pp, manifests/modules/packer/manifests/vsphere/params.pp, manifests/modules/packer/templates/vsphere/ubuntu.rb.erb, templates/ubuntu/18.10/common/files/preseed.cfg, templates/ubuntu/18.10/common/vars.json, templates/ubuntu/18.10/x86_64/vars.json
Added config files for Ubuntu 18.19 x86_64 platform.
This turned out as being useful as it can help test newer versions of Ubuntu before the official release.
=> PUP-9084 Added vars.json for Ubuntu 18.10 x86_64

manifests/modules/packer/manifests/networking/params.pp, manifests/modules/packer/manifests/updates.pp, manifests/modules/packer/manifests/vmtools.pp, manifests/modules/packer/manifests/vmtools/params.pp, manifests/modules/packer/manifests/vsphere.pp, manifests/modules/packer/manifests/vsphere/networking.pp, manifests/modules/packer/manifests/vsphere/params.pp, manifests/modules/packer/manifests/vsphere/repos.pp, manifests/modules/packer/templates/vsphere/solaris.rb.erb, scripts/bootstrap-aio.sh, scripts/cleanup-aio.sh, templates/common/vmware.base.json, templates/common/vmware.vsphere.nocm.json, templates/solaris/11.4/common/files/ai.xml, templates/solaris/11.4/common/files/profile.xml, templates/solaris/11.4/common/vars.json, templates/solaris/11.4/i386/vars.json, templates/solaris/common/vars.json
This PR adds support for Solaris 11.4.
=> [IMAGES-924] add solaris 11.4

manifests/modules/packer/manifests/vmtools.pp, templates/ubuntu/14.04/common/files/preseed.cfg, templates/ubuntu/14.04/i386/vars.json, templates/ubuntu/14.04/x86_64/vars.json, templates/ubuntu/16.04/common/files/preseed.cfg, templates/ubuntu/16.04/i386/vars.json, templates/ubuntu/16.04/x86_64/vars.json, templates/ubuntu/18.04/common/files/preseed.cfg, templates/ubuntu/18.04/x86_64/vars.json, templates/ubuntu/18.10/common/files/preseed.cfg, templates/ubuntu/18.10/x86_64/vars.json
Changed timezone to UTC for ubuntu 18.04, 16.04 and 14.04
=> (IMAGES-802) changed timezone to UTC

templates/win/2008/x86_64/vmware.vcenter.cygwin.json, templates/win/common/vars.json
The build host parameter needs to be abstracted from the win-2008
build also.
=> (IMAGES-896) Fix 2008 build too

templates/win/2008/x86_64/vmware.vcenter.cygwin.json, templates/win/common/vmware.vcenter.cygwin.json
Moving vm_version to 14 (Esx 6.7) as all the VMWare hosts are at
this hardware level.
=> (IMAGES-1000) Update VM Hardware Type

templates/win/common/vars.json
January 2019 Windows Patch Tuesday Rollout
=> (IMAGES-1017) Update the version number

manifests/modules/packer/manifests/vsphere/repos.pp, templates/redhat/7.2-fips/x86_64/vars.json, templates/redhat/7.2/x86_64/vars.json
This was done for the base template, but vsphere was missed.
=> (maint) Update repo url for vsphere templates

manifests/modules/packer/manifests/networking.pp, manifests/modules/packer/manifests/networking/params.pp, manifests/modules/packer/manifests/puppet.pp, manifests/modules/packer/manifests/repos.pp, manifests/modules/packer/manifests/sshd.pp, manifests/modules/packer/manifests/updates.pp, manifests/modules/packer/manifests/vagrant.pp, manifests/modules/packer/manifests/vagrant/params.pp, manifests/modules/packer/manifests/vmtools.pp, manifests/modules/packer/manifests/vmtools/params.pp, manifests/modules/packer/manifests/vsphere.pp, manifests/modules/packer/manifests/vsphere/fw.pp, manifests/modules/packer/manifests/vsphere/networking.pp, manifests/modules/packer/manifests/vsphere/params.pp, manifests/modules/packer/manifests/vsphere/repos.pp, templates/win/common/puppet/windows_group_policy/manifests/gpupdate.pp, templates/win/common/puppet/windows_group_policy/manifests/local/machine_client_side_extensions.pp, templates/win/common/puppet/windows_group_policy/manifests/local/user.pp, templates/win/common/puppet/windows_group_policy/manifests/local/user_client_side_extensions.pp, templates/win/common/puppet/windows_template/manifests/apps/chrome.pp, templates/win/common/puppet/windows_template/manifests/apps/gitforwin.pp, templates/win/common/puppet/windows_template/manifests/apps/notepadplusplus.pp, templates/win/common/puppet/windows_template/manifests/apps/powershell6.pp, templates/win/common/puppet/windows_template/manifests/policies/local_group_policies.pp, templates/win/common/puppet/windows_template/manifests/registry/machine.pp, templates/win/common/scripts/config/win-site.pp
Modified puppet manifests to fix puppet lint warnings & errors.
Please do not merge PR until I test it on CI
=> (IMAGES-1029)-Fix puppet lint issues

templates/win/common/gen-xslt.sh, templates/win/common/vars.json, templates/win/common/vmware.vcenter.bios.base.json, templates/win/common/vmware.vcenter.cygwin.json, templates/win/common/vmware.vcenter.platform9.json
Add additional parameters to support platform9 and fix issues with
_dev_image suffix added to the build pipelines.
=> (IMAGES-1006) Support base/platform9 build

manifests/modules/packer/manifests/vmtools.pp, manifests/modules/packer/manifests/vsphere/networking.pp, manifests/modules/packer/manifests/vsphere/params.pp, manifests/modules/packer/manifests/vsphere/repos.pp, templates/common/vmware.vcenter.json, templates/debian/10.0/common/files/preseed.cfg, templates/debian/10.0/x86_64/vars.json
=> (IMAGES-1025) Add debian-10.0-x86_64 template

templates/debian/10.0/x86_64/vars.json
changed debian 10 template name  from debian-100 to debi…an-10
=> (IMAGES-1025) changed debian 10 template name 

templates/debian/10.0/i386/vars.json
Added support to build debian 10 i386 with packer on vcenter
=> (IMAGES-1056)-Template for Debian 10 i386

templates/win/common/scripts/bootstrap/packer-windows-update.ps1
Having a look at why the last few windows updates fail.
=> (MAINT) Win-2008 update problems

templates/win/common/vars.json
Updating the Windows Version for the April Patch Tuesday event.
=> (IMAGES-1070) April 2019 Patch Tuesday

templates/win/10-1607/x86_64/files/platform-packages.ps1, templates/win/2016-core/x86_64/files/platform-packages.ps1, templates/win/2016-fr/x86_64/files/platform-packages.ps1, templates/win/2016/x86_64/files/platform-packages.ps1
There are new SSU updates for Windows 2016 and Win-10-1607 which need to
be applied to ensure that the windows update happens.
=> (MAINT) Update Win-2016 Servicing stack

manifests/modules/packer/templates/vsphere/redhat.rb.erb, templates/redhat/8.0/x86_64/vars.json
Bump to RedHat 8 final release. Also make this build on vCenter.
=> (IMAGES-1111) Change RedHat 8 image from beta

templates/win/2012r2-fips/x86_64/files/platform-packages.ps1, templates/win/2012r2-fips/x86_64/files/slipstream-filter, templates/win/2012r2-fips/x86_64/vars.json
Create machine image for winfips-2012r2-x64
=> (IMAGES-1137) Create machine image for winfips 2012r2

templates/win/common/vars.json
Windows vmpooler Refresh - Update Version for build.
=> (IMAGES-1174) Jan-2020 Patch Tue Win/vmpooler Refr

templates/centos/common/vars.json, templates/redhat/common/vars.json, templates/sles/common/vars.json, templates/ubuntu/common/vars.json
updated master platforms common files, but individual images will need rebuilt
=> update default disk size from 20GB to 70GB for the vcenter common config

templates/win/common/vmpooler_deploy_record.sh
This is a for record copy of the deploy commands used to deploy the windows vmpooler templates.
I used to hold this privately, but makes sense to keep the record in this repo.
=> (DIO-820) Add Windows vmpooler deploy record

scripts/pdbpreload.sh, templates/centos/8.0-pdbpreload/x86_64/vars.json
This updates the the pdbpreload script (as well as the template vars) to work with creating the image based on 2019.8.
=> (PE-31039) Update pdbpreload script

scripts/pdbpreload.sh
In 2019.8.4, we set up the PE Infrastructure Agent node group to manage master_uris, pcp_broker_list, and server_list. We need to change the values in here to the new hostname as part of the refresh_hostname script.  Post-2019.8.4, we can add this to the refresh_master_hostname plan so we don't need this patch in the bash file we lay down on the image. But for now, this patch will fix the refresh_hostname.sh script on the 2019.8.4-based image.
=> (PE-31039) Fix refresh_hostname script for 2019.8.4

manifests/modules/packer/manifests/repos.pp, templates/redhat/9.0/x86_64/vars.json
This repository adds additional development packages
=> (IMAGES-1322) Add codeready-builder repo to RHEL9

scripts/kurl.sh, templates/redhat/8.4-kurl-beta/common/files/restart_k8s.sh, templates/redhat/8.4-kurl-beta/x86_64/vars.json
Cleans up REPLATS-616 workaround and brings in latest PAM changes.
=> (REPLATS-635) Bump kurl beta pam

templates/redhat/8.4-kurl-beta/common/files/restart_k8s.sh, templates/redhat/8.4-kurl-beta/x86_64/vars.json
Brings in puppetlabs/puppet-application-manager@2022-03-14-rc1
=> (REPLATS-647) Bump kurl-beta vm to version 0.3.13
